import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, BarChart3, CircleDollarSign, Flame, LockKeyhole, Radio, Target, TrendingUp, WalletCards, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SPORTS, betsPool, type Match } from "@/lib/matches";
import { fetchAllMatches } from "@/lib/matches-db";
import { UltraArenaShell, UltraLinkButton, UltraMetric, UltraSection, LiveBadge, TimeBadge } from "@/components/UltraArenaShell";

export const Route = createFileRoute("/betting")({ component: BettingHomePage });

function BettingHomePage() {
  const [matches, setMatches] = useState<Match[]>([]);
  useEffect(() => { let alive = true; const load = () => fetchAllMatches().then((rows) => { if (alive) setMatches(rows); }).catch(() => undefined); void load(); const id = window.setInterval(load, 5000); return () => { alive = false; window.clearInterval(id); }; }, []);
  const open = useMemo(() => matches.filter((m) => !m.endedAt && (m.bets?.length ?? 0) > 0).sort((a, b) => betsPool(b.bets) - betsPool(a.bets)).slice(0, 6), [matches]);
  const pool = open.reduce((sum, m) => sum + betsPool(m.bets), 0);
  return <UltraArenaShell eyebrow="SPORTCHMELÁCI · BETTING OPERATING SYSTEM" title="BETTING" subtitle="Prémiový betting hub pro otevřené zápasy, sázkové pooly a rychlý vstup do existujícího live bet boardu. Server zůstává autoritativní pro výsledky a vypořádání." actions={<><UltraLinkButton href="/bets">LIVE BET BOARD</UltraLinkButton><UltraLinkButton href="/my-bets" primary>MOJE SÁZKY</UltraLinkButton></>}>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><UltraMetric label="OPEN MARKETS" value={String(open.length)} hint="zápasů se sázením" icon={<Target className="h-4 w-4 text-amber-200" />} /><UltraMetric label="TOTAL POOL" value={`$${pool.toLocaleString("en-US")}`} hint="součet dostupných poolů" icon={<CircleDollarSign className="h-4 w-4 text-amber-200" />} /><UltraMetric label="LIVE ENGINE" value="ACTIVE" hint="otevřené sázky se obnovují" icon={<Radio className="h-4 w-4 text-emerald-300" />} /><UltraMetric label="SETTLEMENT" value="SERVER" hint="výsledky rozhoduje match state" icon={<LockKeyhole className="h-4 w-4 text-cyan-200" />} /></div>

    <UltraSection title="FEATURED MARKETS" kicker="HIGH SIGNAL" icon={<Flame className="h-4 w-4 text-amber-200" />} action={<UltraLinkButton href="/bets">OTEVŘÍT BOARD</UltraLinkButton>}>
      {open.length === 0 ? <div className="grid min-h-44 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] text-center"><div><Zap className="mx-auto h-7 w-7 text-amber-200/60" /><div className="mt-2 font-mono text-[10px] font-black uppercase tracking-[.28em] text-white/35">NO OPEN MARKETS</div><div className="mt-1 text-sm text-white/25">Jakmile bude otevřená sázka, objeví se zde.</div></div></div> : <div className="grid gap-3 lg:grid-cols-2">{open.map((match, index) => <MarketCard key={match.id} match={match} featured={index === 0} />)}</div>}
    </UltraSection>

    <UltraSection title="BETTING DESK" kicker="NEXT GEN" icon={<WalletCards className="h-4 w-4 text-cyan-200" />}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Desk href="/bets" title="LIVE BOARD" text="Otevřené, pending a settled tikety na jednom místě." icon={<Radio className="h-5 w-5" />} /><Desk href="/my-bets" title="MY BETS" text="Historie tiketů, výsledky a payouty hráče." icon={<WalletCards className="h-5 w-5" />} /><Desk href="/rankings" title="FORM & ELO" text="Srovnej formu a výsledkový kontext před sázkou." icon={<BarChart3 className="h-5 w-5" />} /><Desk href="/sport-center" title="SPORT CENTER" text="Najdi další zápas a jeho kontext v celém sportovním feedu." icon={<TrendingUp className="h-5 w-5" />} /></div></UltraSection>

    <UltraSection title="ODDS EXPERIENCE" kicker="ROADMAP READY" icon={<TrendingUp className="h-4 w-4 text-cyan-200" />}><div className="grid gap-3 md:grid-cols-3"><Feature title="ODDS MOVEMENT" text="Připravený prostor pro časovou historii kurzů a změnu sentimentu." /><Feature title="BET SLIP" text="Sticky ticket panel pro desktop a bottom sheet pro mobilní zařízení." /><Feature title="PLAYER BETTING PROFILE" text="ROI, win rate, streaks a sportovní preference bez vymýšlení statistik." /></div></UltraSection>
  </UltraArenaShell>;
}

function MarketCard({ match, featured }: { match: Match; featured: boolean }) { const sport = SPORTS[match.sport]; const pool = betsPool(match.bets); const a = match.bets.filter((b) => b.pick === "a").reduce((s, b) => s + (b.amount ?? 0), 0); const b = match.bets.filter((bet) => bet.pick === "b").reduce((s, bet) => s + (bet.amount ?? 0), 0); const pctA = pool ? Math.round((a / pool) * 100) : 50; return <Link to="/match" search={{ id: match.id }} className={`group relative block overflow-hidden rounded-[24px] border bg-black/35 p-5 transition hover:-translate-y-1 ${featured ? "border-amber-300/35 shadow-[0_0_70px_rgba(245,190,60,.10)]" : "border-white/10 hover:border-amber-300/20"}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="text-2xl">{sport.emoji}</span><span className="font-mono text-[9px] uppercase tracking-[.22em] text-white/40">{sport.name}</span><LiveBadge /></div><span className="inline-flex items-center gap-1.5"><TimeBadge>POOL</TimeBadge><span className="font-mono text-[9px] font-black text-amber-100">${pool.toLocaleString("en-US")}</span></span></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="font-display text-lg font-black">{match.teamA}</div><div className="font-mono text-[9px] uppercase tracking-[.22em] text-white/25">VS</div><div className="text-right font-display text-lg font-black">{match.teamB}</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-amber-300 to-amber-100 shadow-[0_0_20px_rgba(245,190,60,.35)]" style={{ width: `${pctA}%` }} /></div><div className="mt-2 flex justify-between font-mono text-[8px] uppercase tracking-[.16em] text-white/25"><span>A {pctA}%</span><span>B {100 - pctA}%</span></div><div className="mt-4 flex items-center justify-between border-t border-white/8 pt-3 font-mono text-[8px] uppercase tracking-[.18em] text-white/30"><span>{match.matchFormat ?? "1v1"} · OPEN</span><span className="inline-flex items-center gap-1 text-amber-200">OPEN MARKET <ArrowUpRight className="h-3.5 w-3.5" /></span></div></Link>; }
function Desk({ href, title, text, icon }: { href: string; title: string; text: string; icon: React.ReactNode }) { return <Link to={href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:-translate-y-1 hover:border-cyan-300/20"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/[.05] text-cyan-200">{icon}</div><div className="mt-4 font-display text-lg font-black tracking-wide">{title}</div><p className="mt-2 text-sm leading-6 text-white/30">{text}</p><div className="mt-4 font-mono text-[8px] uppercase tracking-[.2em] text-cyan-200">OPEN <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></div></Link>; }
function Feature({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.04] to-transparent p-5"><div className="font-display text-lg font-black tracking-wide text-white">{title}</div><p className="mt-2 text-sm leading-6 text-white/30">{text}</p><div className="mt-4 h-px bg-gradient-to-r from-amber-300/30 to-transparent" /></div>; }
