import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, BarChart3, CircleDollarSign, Flame, LockKeyhole, Radio, Target, TrendingUp, WalletCards, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SPORTS, betsPool, type Match } from "@/lib/matches";
import { fetchAllMatches } from "@/lib/matches-db";
import { UltraArenaShell, UltraLinkButton, UltraMetric, UltraSection, LiveBadge, TimeBadge } from "@/components/UltraArenaShell";

export const Route = createFileRoute("/betting")({
  head: () => ({ meta: [{ title: "Betting Hub — SportChmeláci" }, { name: "description", content: "Ultra S+ sportsbook centrum pro otevřené trhy, tikety a betting statistiky." }] }),
  component: BettingHomePage,
});

function BettingHomePage() {
  const [matches, setMatches] = useState<Match[]>([]);
  useEffect(() => { let alive = true; const load = () => fetchAllMatches().then((rows) => { if (alive) setMatches(rows); }).catch(() => undefined); void load(); const id = window.setInterval(load, 5000); return () => { alive = false; window.clearInterval(id); }; }, []);
  const open = useMemo(() => matches.filter((m) => !m.endedAt && (m.bets?.length ?? 0) > 0).sort((a, b) => betsPool(b.bets) - betsPool(a.bets)).slice(0, 8), [matches]);
  const pool = open.reduce((sum, m) => sum + betsPool(m.bets), 0);
  const totalBets = open.reduce((sum, m) => sum + (m.bets?.length ?? 0), 0);
  const live = open.filter((m) => !m.endedAt).length;
  return <UltraArenaShell eyebrow="SPORTCHMELÁCI · BETTING OPERATING SYSTEM" title="BETTING HUB" subtitle="Centrální sportsbook desk pro otevřené trhy, betting pooly, live signály a osobní tikety. Vypořádání zůstává server-authoritative." actions={<><UltraLinkButton href="/bets">LIVE BET BOARD</UltraLinkButton><UltraLinkButton href="/my-bets" primary>MOJE SÁZKY</UltraLinkButton></>}>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <UltraMetric label="OPEN MARKETS" value={String(open.length)} hint="aktivních marketů" icon={<Target className="h-4 w-4 text-amber-200" />} />
      <UltraMetric label="TOTAL POOL" value={`$${pool.toLocaleString("en-US")}`} hint="objem sledovaných poolů" icon={<CircleDollarSign className="h-4 w-4 text-amber-200" />} />
      <UltraMetric label="BET TICKETS" value={String(totalBets)} hint="dohledatelných sázek v otevřených trzích" icon={<WalletCards className="h-4 w-4 text-cyan-200" />} />
      <UltraMetric label="LIVE ENGINE" value={live ? "LIVE" : "READY"} hint="market feed se obnovuje každých 5 s" icon={<Radio className="h-4 w-4 text-emerald-300" />} />
    </div>

    <section className="mt-5 overflow-hidden rounded-[30px] border border-amber-300/15 bg-[radial-gradient(circle_at_12%_0%,rgba(250,204,21,.12),transparent_28%),radial-gradient(circle_at_88%_100%,rgba(34,211,238,.08),transparent_30%),rgba(0,0,0,.24)]">
      <div className="grid gap-0 lg:grid-cols-[1.1fr_.9fr]">
        <div className="p-6 sm:p-9"><div className="flex items-center gap-2 font-mono text-[8px] font-black uppercase tracking-[.28em] text-amber-200/70"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-amber-200" /> ODDS ROOM // ACTIVE</div><h2 className="mt-4 font-display text-5xl font-black tracking-[.07em] text-white sm:text-7xl">THE <span className="gold-text">BETTING DESK</span></h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/40">Vyber market, zkontroluj formu, otevři Match Center a dokonči tiket. Žádný přepis paralelních dat — vše používá existující match a betting engine.</p><div className="mt-6 flex flex-wrap gap-2"><UltraLinkButton href="/bets" primary>OPEN LIVE BOARD</UltraLinkButton><UltraLinkButton href="/my-bets">MY BETS</UltraLinkButton><UltraLinkButton href="/rankings">CHECK FORM</UltraLinkButton></div></div>
        <div className="grid grid-cols-2 border-t border-white/8 lg:border-l lg:border-t-0"><Signal label="MARKETS" value={String(open.length)} /><Signal label="POOL" value={`$${pool.toLocaleString("en-US")}`} /><Signal label="TICKETS" value={String(totalBets)} /><Signal label="SETTLEMENT" value="SERVER" /></div>
      </div>
    </section>

    <UltraSection title="FEATURED MARKETS" kicker="HIGH SIGNAL" icon={<Flame className="h-4 w-4 text-amber-200" />} action={<UltraLinkButton href="/bets">OTEVŘÍT BOARD</UltraLinkButton>}>
      {open.length === 0 ? <Empty title="NO OPEN MARKETS" text="Jakmile bude dostupný otevřený betting market, objeví se zde v reálném čase." /> : <div className="grid gap-3 lg:grid-cols-2">{open.map((match, index) => <MarketCard key={match.id} match={match} featured={index === 0} />)}</div>}
    </UltraSection>

    <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <UltraSection title="BETTING DESK" kicker="COMMAND" icon={<WalletCards className="h-4 w-4 text-cyan-200" />}><div className="grid gap-3 sm:grid-cols-2"><Desk href="/bets" title="LIVE BOARD" text="Otevřené markety a live ticket flow v jednom view." icon={<Radio className="h-5 w-5" />} /><Desk href="/my-bets" title="MY BETS" text="Osobní historie tiketů, stake, payouty a stav vypořádání." icon={<WalletCards className="h-5 w-5" />} /><Desk href="/rankings" title="FORM & ELO" text="Zkontroluj výkon, ELO, formu a vítězné série před sázkou." icon={<BarChart3 className="h-5 w-5" />} /><Desk href="/sport-center" title="SPORT CONTEXT" text="Přejdi do sportovní arény a zjisti live a plánované zápasy." icon={<TrendingUp className="h-5 w-5" />} /></div></UltraSection>
      <UltraSection title="RISK CONTROL" kicker="TRANSPARENCY" icon={<LockKeyhole className="h-4 w-4 text-cyan-200" />}><div className="space-y-3"><Info title="SERVER SETTLEMENT" text="Výsledek a payout určuje potvrzený stav zápasu, ne klientská obrazovka." /><Info title="MAX STAKE" text="Aktuální sportovní limit je $10 000 na tiket." /><Info title="LOCKED ODDS" text="Tiket používá kurz uzamčený při jeho uzavření, pokud ho backend poskytuje." /></div></UltraSection>
    </div>

    <UltraSection title="ODDS EXPERIENCE" kicker="NEXT GEN" icon={<TrendingUp className="h-4 w-4 text-cyan-200" />}><div className="grid gap-3 md:grid-cols-3"><Feature title="ODDS MOVEMENT" text="Připravené místo pro časovou historii kurzů a změnu sentimentu bez změny settlement logiky." /><Feature title="BET SLIP" text="Sticky ticket panel pro desktop a bottom sheet pro mobil — jako další UX vrstva nad existujícím boardem." /><Feature title="PLAYER BETTING PROFILE" text="ROI, hit rate, best sport a streaky pouze z validovaných ticketů." /></div></UltraSection>
  </UltraArenaShell>;
}

function MarketCard({ match, featured }: { match: Match; featured: boolean }) { const sport = SPORTS[match.sport]; const pool = betsPool(match.bets); const a = match.bets.filter((b) => b.pick === "a").reduce((s, b) => s + (b.amount ?? 0), 0); const b = match.bets.filter((bet) => bet.pick === "b").reduce((s, bet) => s + (bet.amount ?? 0), 0); const pctA = pool ? Math.round((a / pool) * 100) : 50; return <Link to="/match" search={{ id: match.id }} className={`group relative block overflow-hidden rounded-[24px] border bg-black/35 p-5 transition hover:-translate-y-1 ${featured ? "border-amber-300/35 shadow-[0_0_70px_rgba(245,190,60,.10)]" : "border-white/10 hover:border-amber-300/20"}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="text-2xl">{sport.emoji}</span><span className="font-mono text-[9px] uppercase tracking-[.22em] text-white/40">{sport.name}</span><LiveBadge /></div><span className="inline-flex items-center gap-1.5"><TimeBadge>POOL</TimeBadge><span className="font-mono text-[9px] font-black text-amber-100">${pool.toLocaleString("en-US")}</span></span></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="font-display text-lg font-black">{match.teamA}</div><div className="font-mono text-[9px] uppercase tracking-[.22em] text-white/25">VS</div><div className="text-right font-display text-lg font-black">{match.teamB}</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-amber-300 to-amber-100 shadow-[0_0_20px_rgba(245,190,60,.35)]" style={{ width: `${pctA}%` }} /></div><div className="mt-2 flex justify-between font-mono text-[8px] uppercase tracking-[.16em] text-white/25"><span>A {pctA}%</span><span>B {100 - pctA}%</span></div><div className="mt-4 flex items-center justify-between border-t border-white/8 pt-3 font-mono text-[8px] uppercase tracking-[.18em] text-white/30"><span>{match.matchFormat ?? "1v1"} · OPEN</span><span className="inline-flex items-center gap-1 text-amber-200">OPEN MARKET <ArrowUpRight className="h-3.5 w-3.5" /></span></div></Link>; }
function Desk({ href, title, text, icon }: { href: string; title: string; text: string; icon: React.ReactNode }) { return <Link to={href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:-translate-y-1 hover:border-cyan-300/20"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/[.05] text-cyan-200">{icon}</div><div className="mt-4 font-display text-lg font-black tracking-wide">{title}</div><p className="mt-2 text-sm leading-6 text-white/30">{text}</p><div className="mt-4 font-mono text-[8px] uppercase tracking-[.2em] text-cyan-200">OPEN <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></div></Link>; }
function Feature({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.04] to-transparent p-5"><div className="font-display text-lg font-black tracking-wide text-white">{title}</div><p className="mt-2 text-sm leading-6 text-white/30">{text}</p><div className="mt-4 h-px bg-gradient-to-r from-amber-300/30 to-transparent" /></div>; }
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="font-mono text-[8px] font-black uppercase tracking-[.24em] text-cyan-200/60">{title}</div><p className="mt-2 text-sm leading-6 text-white/35">{text}</p></div>; }
function Signal({ label, value }: { label: string; value: string }) { return <div className="border-white/8 p-5"><div className="font-mono text-[8px] uppercase tracking-[.22em] text-white/30">{label}</div><div className="mt-2 break-words font-display text-2xl font-black text-white">{value}</div></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="grid min-h-40 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] text-center"><div><Zap className="mx-auto h-7 w-7 text-amber-200/60" /><div className="mt-2 font-mono text-[10px] font-black uppercase tracking-[.28em] text-white/35">{title}</div><div className="mt-1 text-sm text-white/25">{text}</div></div></div>; }
