import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, ChevronRight, Radio, Swords, Users, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SPORTS, type Match } from "@/lib/matches";
import { fetchAllMatches } from "@/lib/matches-db";
import { UltraArenaShell, UltraLinkButton, UltraMetric, UltraSection, LiveBadge, PowerMark } from "@/components/UltraArenaShell";

export const Route = createFileRoute("/live-arena")({ component: LiveArenaPage });

function LiveArenaPage() {
  const [matches, setMatches] = useState<Match[]>([]);
  useEffect(() => { let alive = true; const load = () => fetchAllMatches().then((rows) => { if (alive) setMatches(rows.filter((m) => !m.endedAt).slice(0, 20)); }).catch(() => undefined); void load(); const id = window.setInterval(load, 2500); return () => { alive = false; window.clearInterval(id); }; }, []);
  return <UltraArenaShell eyebrow="SPORTCHMELÁCI · REALTIME" title="LIVE ARENA" accent="cyan" subtitle="Centrální televizní feed otevřených zápasů. Score, sety, formát a týmové sestavy se obnovují z aktuálního match feedu." actions={<><UltraLinkButton href="/sport-center">SPORT CENTER</UltraLinkButton><UltraLinkButton href="/bets" primary>SLEDOVAT SÁZKY</UltraLinkButton></>}>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><UltraMetric label="LIVE NOW" value={String(matches.length)} hint="otevřených match feedů" icon={<Radio className="h-4 w-4 text-emerald-300" />} /><UltraMetric label="FORMAT" value="1V1 / 2V2" hint="individuální i týmové zápasy" icon={<Users className="h-4 w-4 text-cyan-200" />} /><UltraMetric label="REFRESH" value="2.5 SEC" hint="rychlý přehled aktuálního stavu" icon={<Activity className="h-4 w-4 text-cyan-200" />} /></div>
    <UltraSection title="NOW PLAYING" kicker="LIVE GRID" icon={<PowerMark />}>{matches.length === 0 ? <Empty /> : <div className="grid gap-4 xl:grid-cols-2">{matches.map((match, index) => <LiveMatch key={match.id} match={match} featured={index === 0} />)}</div>}</UltraSection>
  </UltraArenaShell>;
}

function LiveMatch({ match, featured }: { match: Match; featured: boolean }) {
  const sport = SPORTS[match.sport]; const format = match.matchFormat ?? "1v1";
  return <Link to="/match" search={{ id: match.id }} className={`group relative block overflow-hidden rounded-[24px] border bg-black/35 p-5 transition hover:-translate-y-1 ${featured ? "border-amber-300/35 shadow-[0_0_70px_rgba(245,190,60,.10)]" : "border-white/10 hover:border-cyan-300/25"}`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(34,211,238,.08),transparent_25%)]" /><div className="relative"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="text-2xl">{sport.emoji}</span><span className="font-mono text-[9px] uppercase tracking-[.24em] text-white/40">{sport.name}</span><LiveBadge /></div><span className="rounded-full border border-white/10 bg-white/[.03] px-2 py-1 font-mono text-[8px] uppercase tracking-[.2em] text-white/30">{format}</span></div><div className="mt-6 grid grid-cols-[1fr_auto_1fr] items-center gap-4"><div><div className="font-mono text-[8px] uppercase tracking-[.2em] text-white/25">TEAM A</div><div className="mt-1 truncate font-display text-2xl font-black tracking-wide">{match.teamA}</div>{format === "2v2" && match.teamAPlayers ? <div className="mt-1 truncate text-[10px] text-white/30">{match.teamAPlayers.join(" · ")}</div> : null}</div><div className="text-center"><div className="font-mono text-[9px] uppercase tracking-[.2em] text-white/25">SCORE</div><div className="mt-1 rounded-2xl border border-amber-300/25 bg-amber-300/[.06] px-4 py-3 font-display text-3xl font-black tracking-wider text-amber-100">{match.scoreA}:{match.scoreB}</div>{match.sets.length ? <div className="mt-2 font-mono text-[9px] uppercase tracking-[.16em] text-white/30">{match.sets.map((s) => `${s.a}-${s.b}`).join(" · ")}</div> : null}</div><div className="text-right"><div className="font-mono text-[8px] uppercase tracking-[.2em] text-white/25">TEAM B</div><div className="mt-1 truncate font-display text-2xl font-black tracking-wide">{match.teamB}</div>{format === "2v2" && match.teamBPlayers ? <div className="mt-1 truncate text-[10px] text-white/30">{match.teamBPlayers.join(" · ")}</div> : null}</div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-2 border-t border-white/8 pt-3"><div className="flex items-center gap-2 font-mono text-[8px] uppercase tracking-[.18em] text-white/30"><Swords className="h-3.5 w-3.5 text-amber-200" /> {featured ? "FEATURED LIVE" : "OPEN MATCH"}</div><span className="inline-flex items-center gap-1 font-mono text-[8px] uppercase tracking-[.18em] text-cyan-200">OPEN MATCH <ChevronRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></div></div></Link>;
}

function Empty() { return <div className="grid min-h-56 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] text-center"><div><Zap className="mx-auto h-7 w-7 text-cyan-200/60" /><div className="mt-2 font-mono text-[10px] font-black uppercase tracking-[.3em] text-white/35">NO ACTIVE SIGNAL</div><div className="mt-1 max-w-sm text-sm text-white/25">Jakmile začne další zápas, jeho live feed se objeví tady.</div></div></div>; }
