import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, Crown, Flame, Medal, Radio, Sparkles, Trophy, Users, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fetchAllMatches } from "@/lib/matches-db";
import { SPORTS, SPORT_LIST, type Match } from "@/lib/matches";
import { SportFilterBar } from "@/components/SportFilterBar";
import { splitPlayers, winnerSideOf } from "@/lib/stats";
import { UltraArenaShell, UltraLinkButton, UltraMetric, UltraSection } from "@/components/UltraArenaShell";

export const Route = createFileRoute("/records")({
  head: () => ({ meta: [{ title: "Rekordy — Chmeloví Sportovci" }, { name: "description", content: "Síň slávy, série, sportovní rekordy a nejlepší výkony." }] }),
  component: RecordsPage,
});

type PlayerRecord = { key: string; name: string; wins: number; losses: number; played: number; winRate: number; streak: number; bestStreak: number };

type SportRecord = { id: string; name: string; emoji: string; matches: number; leader?: PlayerRecord };

function RecordsPage() {
  const [matches, setMatches] = useState<Match[]>([]);
  const [sport, setSport] = useState<string>("all");
  useEffect(() => { let alive = true; const load = async () => { try { const rows = await fetchAllMatches(); if (alive) setMatches(rows); } catch { if (alive) setMatches([]); } }; void load(); const id = window.setInterval(() => void load(), 5000); return () => { alive = false; window.clearInterval(id); }; }, []);

  const completed = useMemo(() => matches.filter((m) => !!m.endedAt && (sport === "all" || m.sport === sport)).sort((a, b) => Number(a.endedAt ?? 0) - Number(b.endedAt ?? 0)), [matches, sport]);
  const playerRecords = useMemo(() => buildPlayerRecords(completed), [completed]);
  const topWins = [...playerRecords].sort((a, b) => b.wins - a.wins || b.winRate - a.winRate)[0];
  const topStreak = [...playerRecords].sort((a, b) => b.bestStreak - a.bestStreak || b.wins - a.wins)[0];
  const topRate = [...playerRecords].filter((r) => r.played >= 3).sort((a, b) => b.winRate - a.winRate || b.wins - a.wins)[0];
  const biggest2v2 = completed.filter((m) => m.matchFormat === "2v2").sort((a, b) => (splitPlayers(b.teamA).length + splitPlayers(b.teamB).length) - (splitPlayers(a.teamA).length + splitPlayers(a.teamB).length))[0];
  const sportRecords: SportRecord[] = useMemo(() => SPORT_LIST.map((s) => { const sportMatches = matches.filter((m) => !!m.endedAt && m.sport === s.id); const rows = buildPlayerRecords(sportMatches); return { id: s.id, name: s.name, emoji: s.emoji, matches: sportMatches.length, leader: rows[0] }; }).filter((s) => s.matches > 0), [matches]);

  return <UltraArenaShell eyebrow="CHMELOVÍ SPORTOVCI · SÍŇ SLÁVY" title="REKORDY" subtitle="Historické výkony z dokončených zápasů. Série, vítězní hráči a nejlepší výsledky jednotlivých sportů na jednom místě." actions={<><UltraLinkButton href="/rankings">SCOREBOARD</UltraLinkButton><UltraLinkButton href="/sport-center" primary>SPORT CENTRUM</UltraLinkButton></>}>
    <div className="mt-6 flex max-w-full gap-2 overflow-x-auto pb-1"><SportFilterBar value={sport as never} onChange={(v) => setSport(v)} allLabel="Všechny sporty" /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><UltraMetric label="DOKONČENÉ" value={String(completed.length)} hint="ověřených zápasů" icon={<Radio className="h-4 w-4 text-emerald-300" />} /><UltraMetric label="STROJ NA VÝHRY" value={topWins?.name ?? "—"} hint={topWins ? `${topWins.wins} výher` : "čekáme na data"} icon={<Trophy className="h-4 w-4 text-amber-200" />} /><UltraMetric label="NEJDELŠÍ SÉRIE" value={topStreak?.name ?? "—"} hint={topStreak ? `${topStreak.bestStreak} výher v řadě` : "čekáme na data"} icon={<Flame className="h-4 w-4 text-orange-300" />} /><UltraMetric label="2V2" value={biggest2v2 ? `${splitPlayers(biggest2v2.teamA).length + splitPlayers(biggest2v2.teamB).length} HRÁČŮ` : "PŘIPRAVENO"} hint="největší týmové obsazení" icon={<Users className="h-4 w-4 text-cyan-200" />} /></div>

    <section className="mt-5 overflow-hidden rounded-[30px] border border-amber-300/15 bg-[radial-gradient(circle_at_15%_0%,rgba(250,204,21,.12),transparent_28%),radial-gradient(circle_at_85%_100%,rgba(34,211,238,.08),transparent_30%),rgba(0,0,0,.24)]"><div className="grid gap-0 lg:grid-cols-[1.15fr_.85fr]"><div className="p-6 sm:p-9"><div className="flex items-center gap-2 font-mono text-[8px] font-black uppercase tracking-[.26em] text-amber-200/70"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-amber-200" /> RECORD PROTOCOL · AKTIVNÍ</div><h2 className="mt-4 font-display text-5xl font-black tracking-[.08em] text-white sm:text-7xl">SÍŇ <span className="gold-text">SLÁVY</span></h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/40">Největší výkony SportChmeláků. Vyber sport a sleduj jeho vlastní rekordní stopu.</p><div className="mt-5 flex flex-wrap gap-2"><UltraLinkButton href="/trophy-room" primary>TROPHY ROOM</UltraLinkButton><UltraLinkButton href="/leagues">CHMEL LEAGUE</UltraLinkButton><UltraLinkButton href="/activity">ŽIVÉ DĚNÍ</UltraLinkButton></div></div><div className="grid grid-cols-2 border-t border-white/8 lg:border-l lg:border-t-0"><Signal label="HRÁČI" value={String(playerRecords.length)} icon={<Medal className="h-4 w-4" />} /><Signal label="NEJLEPŠÍ ÚSPĚŠNOST" value={topRate ? `${Math.round(topRate.winRate * 100)} %` : "—"} icon={<Sparkles className="h-4 w-4" />} /><Signal label="SPORTY" value={String(sportRecords.length)} icon={<Trophy className="h-4 w-4" />} /><Signal label="LIVE PROPOJENÍ" value="AKTIVNÍ" icon={<Zap className="h-4 w-4" />} /></div></div></section>

    <UltraSection title="REKORDNÍ TITÁNI" kicker="CELKEM" icon={<Crown className="h-4 w-4 text-amber-200" />}><div className="grid gap-3 md:grid-cols-3"><RecordCard icon={<Trophy className="h-5 w-5" />} title="STROJ NA VÝHRY" name={topWins?.name ?? "BEZ DAT"} value={topWins ? `${topWins.wins} V` : "—"} hint={topWins ? `${topWins.played} zápasů · ${Math.round(topWins.winRate * 100)} % úspěšnost` : "čekáme na dokončené zápasy"} /><RecordCard icon={<Flame className="h-5 w-5" />} title="KRÁL SÉRIE" name={topStreak?.name ?? "BEZ DAT"} value={topStreak ? `${topStreak.bestStreak} V` : "—"} hint={topStreak ? `aktuální série ${topStreak.streak}` : "čekáme na data o formě"} /><RecordCard icon={<Sparkles className="h-5 w-5" />} title="KRÁL ÚSPĚŠNOSTI" name={topRate?.name ?? "BEZ DAT"} value={topRate ? `${Math.round(topRate.winRate * 100)} %` : "—"} hint={topRate ? `${topRate.wins} V / ${topRate.losses} P · minimum 3 zápasy` : "minimum tři zápasy"} /></div></UltraSection>

    <UltraSection title="KRÁLOVÉ SPORTŮ" kicker="PODLE DISCIPLÍNY" icon={<Trophy className="h-4 w-4 text-cyan-200" />}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{sportRecords.map((s) => <button key={s.id} onClick={() => setSport(s.id)} className="group rounded-2xl border border-white/8 bg-white/[.02] p-4 text-left transition hover:-translate-y-0.5 hover:border-cyan-300/25"><div className="flex items-center justify-between"><span className="text-3xl">{s.emoji}</span><span className="font-mono text-[8px] uppercase tracking-[.18em] text-white/25">{s.matches} ZÁPASŮ</span></div><div className="mt-4 font-display text-xl font-black tracking-wide text-white">{s.name}</div><div className="mt-2 text-sm text-white/35">{s.leader ? <><span className="text-cyan-200">{s.leader.name}</span> · {s.leader.wins} V · {Math.round(s.leader.winRate * 100)} %</> : "Bez lídra"}</div><div className="mt-3 font-mono text-[8px] uppercase tracking-[.2em] text-cyan-200/60">OTEVŘÍT ARÉNU →</div></button>)}</div>{sportRecords.length === 0 && <Empty text="Sportovní rekordy zatím nejsou k dispozici." />}</UltraSection>

    <UltraSection title="REKORDNÍ MOMENTY" kicker="ARCHIV ZÁPASŮ" icon={<CalendarDays className="h-4 w-4 text-amber-200" />}><div className="grid gap-3 md:grid-cols-2">{completed.slice(-6).reverse().map((m) => <Link key={m.id} to="/match" search={{ id: m.id }} className="group rounded-2xl border border-white/8 bg-white/[.02] p-4 hover:border-amber-300/25"><div className="flex items-center justify-between gap-3"><span className="font-mono text-[8px] uppercase tracking-[.18em] text-white/30">{SPORTS[m.sport].emoji} {SPORTS[m.sport].name}</span><span className="font-mono text-[8px] text-white/20">{m.endedAt ? new Date(m.endedAt).toLocaleDateString("cs-CZ") : ""}</span></div><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><span className="truncate font-display text-base text-white">{m.teamA}</span><span className="rounded-xl border border-amber-300/15 bg-amber-300/[.05] px-2.5 py-1.5 font-mono text-sm text-amber-100">{m.scoreA}:{m.scoreB}</span><span className="truncate text-right font-display text-base text-white">{m.teamB}</span></div></Link>)}</div>{completed.length === 0 && <Empty text="Po dokončení zápasů se zde objeví historické momenty." />}</UltraSection>

    <div className="mt-6 flex flex-wrap justify-center gap-2"><UltraLinkButton href="/rankings" primary>CELÝ SCOREBOARD</UltraLinkButton><UltraLinkButton href="/sport-center">SPORT CENTRUM</UltraLinkButton><UltraLinkButton href="/trophy-room">TROPHY ROOM</UltraLinkButton></div>
  </UltraArenaShell>;
}

function buildPlayerRecords(matches: Match[]): PlayerRecord[] { const map = new Map<string, PlayerRecord>(); const ordered = [...matches].sort((a, b) => Number(a.endedAt ?? 0) - Number(b.endedAt ?? 0)); for (const m of ordered) { const winner = winnerSideOf(m); if (!winner) continue; const seen = new Set<string>(); for (const side of ["a", "b"] as const) for (const name of splitPlayers(side === "a" ? m.teamA : m.teamB)) { const key = name.trim().toLowerCase(); if (!key || seen.has(key)) continue; seen.add(key); const r = map.get(key) ?? { key, name: name.trim(), wins: 0, losses: 0, played: 0, winRate: 0, streak: 0, bestStreak: 0 }; r.played++; if (side === winner) { r.wins++; r.streak++; r.bestStreak = Math.max(r.bestStreak, r.streak); } else { r.losses++; r.streak = 0; } r.winRate = r.played ? r.wins / r.played : 0; map.set(key, r); } } return [...map.values()].sort((a, b) => b.wins - a.wins || b.bestStreak - a.bestStreak || b.winRate - a.winRate || a.name.localeCompare(b.name)); }
function Signal({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="p-5"><div className="flex items-center gap-2 text-white/30"><span className="text-amber-200/80">{icon}</span><span className="font-mono text-[8px] uppercase tracking-[.22em]">{label}</span></div><div className="mt-2 font-display text-2xl font-black text-white">{value}</div></div>; }
function RecordCard({ icon, title, name, value, hint }: { icon: React.ReactNode; title: string; name: string; value: string; hint: string }) { return <div className="relative overflow-hidden rounded-2xl border border-amber-300/15 bg-gradient-to-br from-amber-300/[.06] to-transparent p-5"><div className="grid h-10 w-10 place-items-center rounded-xl border border-amber-300/20 bg-amber-300/10 text-amber-200">{icon}</div><div className="mt-5 font-mono text-[8px] uppercase tracking-[.25em] text-amber-200/50">{title}</div><div className="mt-1 truncate font-display text-xl font-black tracking-wide text-white">{name}</div><div className="mt-2 font-display text-3xl font-black text-amber-100">{value}</div><p className="mt-2 text-sm leading-6 text-white/30">{hint}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-28 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] p-6 text-center font-mono text-[9px] uppercase tracking-[.18em] text-white/25">{text}</div>; }
