import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, BarChart3, CalendarDays, Crown, Flame, Medal, Radio, Shield, Sparkles, Trophy, Users, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SPORTS, SPORT_LIST, type Match, type SportId } from "@/lib/matches";
import { fetchAllMatches } from "@/lib/matches-db";
import { splitPlayers } from "@/lib/stats";
import { UltraArenaShell, UltraLinkButton, UltraMetric, UltraSection, LiveBadge, TimeBadge, PowerMark } from "@/components/UltraArenaShell";

export const Route = createFileRoute("/sport-center")({
  head: () => ({ meta: [{ title: "Sport centrum — Chmeloví Sportovci" }, { name: "description", content: "Prémiové sportovní centrum pro živé zápasy, formu, žebříčky a rekordy." }] }),
  component: SportCenterPage,
});

type PlayerStat = { name: string; played: number; wins: number; losses: number; winRate: number };
const matchPlayers = (m: Match) => [...splitPlayers(String(m.teamA)), ...splitPlayers(String(m.teamB))];

function SportCenterPage() {
  const [matches, setMatches] = useState<Match[]>([]);
  const [sport, setSport] = useState<SportId | "all">("all");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    const load = async () => {
      try { const rows = await fetchAllMatches(); if (alive) setMatches(rows); }
      finally { if (alive) setLoading(false); }
    };
    void load();
    const id = window.setInterval(() => void load(), 5000);
    return () => { alive = false; window.clearInterval(id); };
  }, []);

  const filtered = useMemo(() => sport === "all" ? matches : matches.filter((m) => m.sport === sport), [matches, sport]);
  const completed = useMemo(() => filtered.filter((m) => !!m.endedAt), [filtered]);
  const live = useMemo(() => filtered.filter((m) => !m.endedAt).slice(0, 6), [filtered]);
  const upcoming = useMemo(() => filtered.filter((m) => !m.endedAt && m.scheduledAt).sort((a, b) => Number(a.scheduledAt) - Number(b.scheduledAt)).slice(0, 6), [filtered]);
  const sportCounts = SPORT_LIST.map((item) => ({ ...item, count: matches.filter((m) => m.sport === item.id).length, live: matches.filter((m) => m.sport === item.id && !m.endedAt).length }));
  const playerStats = useMemo(() => buildPlayerStats(completed), [completed]);
  const currentSport = sport === "all" ? null : SPORTS[sport];
  const selectedSummary = sport === "all"
    ? { matches: matches.length, live: matches.filter((m) => !m.endedAt).length, players: uniquePlayers(matches).size }
    : { matches: filtered.length, live: live.length, players: uniquePlayers(filtered).size };

  return <UltraArenaShell eyebrow="CHMELOVÍ SPORTOVCI · SPORTOVNÍ SYSTÉM" title="SPORT CENTRUM" subtitle="Vyber disciplínu, sleduj živé dění a otevři rovnou její zápasy, formu, rekordy nebo žebříček." actions={<><UltraLinkButton href="/schedule">PLÁN ZÁPASŮ</UltraLinkButton><UltraLinkButton href="/rankings" primary>ŽEBŘÍČKY</UltraLinkButton></>}>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><UltraMetric label="ZÁPASY" value={loading ? "—" : String(selectedSummary.matches)} hint="v aktivním sportovním feedu" icon={<Radio className="h-4 w-4 text-emerald-300" />} /><UltraMetric label="ŽIVĚ" value={String(selectedSummary.live)} hint="otevřených soubojů právě teď" icon={<Flame className="h-4 w-4 text-amber-200" />} /><UltraMetric label="HRÁČI" value={String(selectedSummary.players)} hint="unikátních hráčů ve feedu" icon={<Users className="h-4 w-4 text-cyan-200" />} /><UltraMetric label="FORMÁTY" value="1V1 / 2V2" hint="sólo i týmová konkurence" icon={<Shield className="h-4 w-4 text-violet-200" />} /></div>

    <UltraSection title="SPORTOVNÍ UNIVERZUM" kicker="VYBER ARÉNU" icon={<PowerMark />}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{sportCounts.slice(0, 8).map((s) => <button key={s.id} onClick={() => setSport(s.id)} className={`group relative min-h-40 overflow-hidden rounded-2xl border p-4 text-left transition duration-300 hover:-translate-y-1 ${sport === s.id ? "border-amber-300/60 bg-amber-300/[.1] shadow-[0_0_50px_rgba(245,190,60,.14)]" : "border-white/10 bg-white/[.025] hover:border-white/20"}`}><div className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-amber-300/10 blur-3xl transition group-hover:bg-cyan-300/10" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><span className="text-4xl">{s.emoji}</span><div className="flex items-center gap-1.5">{s.live > 0 && <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300" />}<span className="font-mono text-[8px] uppercase tracking-[.2em] text-white/30">{s.count} ZÁPASŮ</span></div></div><div><div className="font-display text-xl font-black tracking-wider text-white">{s.name}</div><div className="mt-1 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.18em] text-white/35">OTEVŘÍT ARÉNU <ArrowUpRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></div></div></div></button>)}</div></UltraSection>

    <section className="mt-4 overflow-hidden rounded-[28px] border border-cyan-300/15 bg-[radial-gradient(circle_at_10%_0%,rgba(34,211,238,.1),transparent_28%),radial-gradient(circle_at_90%_90%,rgba(250,204,21,.08),transparent_28%),rgba(0,0,0,.22)]"><div className="grid gap-0 lg:grid-cols-[1.1fr_.9fr]"><div className="p-6 sm:p-8"><div className="flex flex-wrap items-center gap-2"><span className="aaa-meta text-cyan-200/80">IDENTITA ARÉNY</span>{currentSport ? <span className="rounded-full border border-cyan-300/20 bg-cyan-300/5 px-2.5 py-1 font-mono text-[8px] font-black uppercase tracking-[.18em] text-cyan-200">{currentSport.emoji} {currentSport.name}</span> : <span className="rounded-full border border-amber-300/20 bg-amber-300/5 px-2.5 py-1 font-mono text-[8px] font-black uppercase tracking-[.18em] text-amber-200">VŠECHNY SPORTY</span>}</div><h2 className="mt-4 font-display text-5xl font-black tracking-[.06em] text-white sm:text-6xl">{currentSport?.name.toUpperCase() ?? "VŠE V JEDNOM"}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/40">{currentSport ? `Kompletní centrum pro ${currentSport.name.toLowerCase()}: živé zápasy, nejlepší hráči, naplánované souboje a historické výkony.` : "Globální pohled přes všechny disciplíny s jednotným live feedem a rychlou cestou do konkrétní sportovní arény."}</p><div className="mt-6 flex flex-wrap gap-2"><UltraLinkButton href="/live">ŽIVÁ ARÉNA</UltraLinkButton><UltraLinkButton href="/rankings" primary>SCOREBOARD</UltraLinkButton>{currentSport ? <UltraLinkButton href="/schedule">DALŠÍ ZÁPAS</UltraLinkButton> : null}</div></div><div className="grid grid-cols-2 border-t border-white/8 sm:grid-cols-4 lg:grid-cols-2 lg:border-l lg:border-t-0"><Signal label="ZÁPASY" value={selectedSummary.matches} icon={<Trophy className="h-4 w-4" />} /><Signal label="ŽIVĚ" value={selectedSummary.live} icon={<Radio className="h-4 w-4" />} /><Signal label="HRÁČI" value={selectedSummary.players} icon={<Users className="h-4 w-4" />} /><Signal label="2V2" value={filtered.filter((m) => m.matchFormat === "2v2").length} icon={<Shield className="h-4 w-4" />} /></div></div></section>

    <UltraSection title="ŽIVÁ ARÉNA" kicker="PRÁVĚ TEĎ" icon={<Radio className="h-4 w-4 text-emerald-300" />} action={<UltraLinkButton href="/live">VSTOUPIT DO LIVE</UltraLinkButton>}>{live.length === 0 ? <EmptyState title="ŽÁDNÝ ŽIVÝ ZÁPAS" text="Jakmile bude otevřený zápas, zobrazí se zde automaticky." /> : <div className="grid gap-3 lg:grid-cols-2">{live.map((m) => <MatchCard key={m.id} match={m} live />)}</div>}</UltraSection>

    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><UltraSection title="ŽEBŘÍČEK SPORTU" kicker="VÝKON A FORMA" icon={<Crown className="h-4 w-4 text-amber-200" />} action={<UltraLinkButton href="/rankings">CELÝ ŽEBŘÍČEK</UltraLinkButton>}>{playerStats.length === 0 ? <EmptyState title="ČEKÁME NA VÝSLEDKY" text="Hráči se objeví po prvních dokončených zápasech." /> : <div className="space-y-2">{playerStats.slice(0, 6).map((p, i) => <PlayerRow key={p.name} player={p} rank={i + 1} />)}</div>}</UltraSection><UltraSection title="DALŠÍ ZÁPAS" kicker="NAPLÁNOVÁNO" icon={<CalendarDays className="h-4 w-4 text-cyan-200" />}>{upcoming.length === 0 ? <EmptyState title="NIC NENÍ NAPLÁNOVÁNO" text="Jakmile přibude další termín, zobrazí se zde." /> : <div className="space-y-2">{upcoming.map((m) => <Link key={m.id} to="/match" search={{ id: m.id }} className="group block rounded-2xl border border-white/8 bg-white/[.02] p-3 hover:border-cyan-300/25"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate font-display text-base tracking-wide text-white">{m.teamA} <span className="text-white/20">VS</span> {m.teamB}</div><div className="aaa-meta mt-1">{SPORTS[m.sport].name} · {m.matchFormat === "2v2" ? "2V2 · TÝMY" : "1V1 · SÓLO"}</div></div><TimeBadge>{new Date(m.scheduledAt!).toLocaleString("cs-CZ", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</TimeBadge></div></Link>)}</div>}</UltraSection></div>

    <UltraSection title="HALA SLÁVY" kicker="REKORDNÍ SIGNÁL" icon={<Medal className="h-4 w-4 text-amber-200" />} action={<UltraLinkButton href="/records">VŠECHNY REKORDY</UltraLinkButton>}><div className="grid gap-3 sm:grid-cols-3"><RecordTile icon={<Trophy className="h-5 w-5" />} label="STROJ NA VÝHRY" value={playerStats[0]?.name ?? "—"} hint={playerStats[0] ? `${playerStats[0].wins} výher` : "čekáme"} /><RecordTile icon={<Flame className="h-5 w-5" />} label="KRÁL FORMY" value={[...playerStats].sort((a, b) => b.winRate - a.winRate)[0]?.name ?? "—"} hint={playerStats.length ? `${Math.round(([...playerStats].sort((a, b) => b.winRate - a.winRate)[0]?.winRate ?? 0) * 100)} % úspěšnost` : "čekáme"} /><RecordTile icon={<Sparkles className="h-5 w-5" />} label="TÝMOVÝ SIGNÁL" value={filtered.some((m) => m.matchFormat === "2v2") ? "AKTIVNÍ" : "PŘIPRAVEN"} hint="aréna 2V2" /></div></UltraSection>

    <UltraSection title="NAPLÁNUJ DALŠÍ SOUBOJ" kicker="MATCH BUILDER" icon={<Zap className="h-4 w-4 text-amber-200" />}><div className="grid gap-3 md:grid-cols-3"><MiniPanel title="1V1" value="SÓLO" text="Klasický duel s vlastní historií a osobním výkonem." href="/schedule" /><MiniPanel title="2V2" value="TÝMY" text="Týmový souboj navázaný na soupisky a historii 2V2." href="/schedule" /><MiniPanel title="H2H" value="PROTI SOBĚ" text="Porovnej formu před dalším přímým střetem." href="/rankings" /></div></UltraSection>
    <div className="mt-6 flex flex-wrap justify-center gap-2"><UltraLinkButton href="/leagues">CHMEL LEAGUE</UltraLinkButton><UltraLinkButton href="/activity" primary>ŽIVÉ DĚNÍ</UltraLinkButton><UltraLinkButton href="/trophy-room">TROPHY ROOM</UltraLinkButton></div>
  </UltraArenaShell>;
}

function uniquePlayers(matches: Match[]) { const names = new Set<string>(); matches.forEach((m) => matchPlayers(m).forEach((n) => { const key = n.trim().toLowerCase(); if (key) names.add(key); })); return names; }
function buildPlayerStats(matches: Match[]): PlayerStat[] { const map = new Map<string, { label: string; played: number; wins: number; losses: number }>(); for (const m of matches) { const winner = m.scoreA === m.scoreB ? null : m.scoreA > m.scoreB ? "a" : "b"; for (const name of matchPlayers(m)) { const key = name.trim().toLowerCase(); if (!key) continue; const row = map.get(key) ?? { label: name.trim(), played: 0, wins: 0, losses: 0 }; row.played++; const a = splitPlayers(String(m.teamA)).some((n) => n.toLowerCase() === key); const b = splitPlayers(String(m.teamB)).some((n) => n.toLowerCase() === key); if (winner === "a" && a) row.wins++; else if (winner === "b" && b) row.wins++; else if (winner) row.losses++; map.set(key, row); } } return [...map.values()].map((r) => ({ name: r.label, played: r.played, wins: r.wins, losses: r.losses, winRate: r.played ? r.wins / r.played : 0 })).sort((a, b) => b.wins - a.wins || b.winRate - a.winRate || b.played - a.played); }
function Signal({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="p-5"><div className="flex items-center gap-2 text-white/30"><span className="text-amber-200/80">{icon}</span><span className="aaa-meta">{label}</span></div><div className="mt-2 font-display text-3xl font-black text-white">{value}</div></div>; }
function PlayerRow({ player, rank }: { player: PlayerStat; rank: number }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.02] p-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-amber-300/20 bg-amber-300/[.06] font-mono text-xs font-black text-amber-200">{String(rank).padStart(2, "0")}</span><div className="min-w-0 flex-1"><div className="truncate font-display text-base font-black tracking-wide text-white">{player.name}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 via-amber-200 to-amber-300" style={{ width: `${Math.max(5, Math.min(100, player.winRate * 100))}%` }} /></div></div><div className="text-right"><div className="font-mono text-xs font-black text-white">{Math.round(player.winRate * 100)}%</div><div className="font-mono text-[8px] text-white/25">{player.wins} V / {player.losses} P</div></div></div>; }
function RecordTile({ icon, label, value, hint }: { icon: React.ReactNode; label: string; value: string; hint: string }) { return <div className="rounded-2xl border border-amber-300/12 bg-amber-300/[.025] p-5"><div className="grid h-10 w-10 place-items-center rounded-xl border border-amber-300/20 bg-amber-300/10 text-amber-200">{icon}</div><div className="mt-4 aaa-meta text-amber-200/60">{label}</div><div className="mt-1 truncate font-display text-xl font-black text-white">{value}</div><div className="mt-1 font-mono text-[9px] text-white/25">{hint}</div></div>; }
function MiniPanel({ title, value, text, href }: { title: string; value: string; text: string; href: string }) { return <Link to={href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:-translate-y-0.5 hover:border-amber-300/25"><div className="font-mono text-[8px] uppercase tracking-[.28em] text-white/30">{title}</div><div className="mt-2 flex items-center justify-between font-display text-2xl font-black text-amber-100"><span>{value}</span><ArrowUpRight className="h-4 w-4 text-white/20 transition group-hover:text-amber-200" /></div><div className="mt-2 text-sm leading-6 text-white/35">{text}</div></Link>; }
function MatchCard({ match, live = false }: { match: Match; live?: boolean }) { const sport = SPORTS[match.sport]; return <Link to="/match" search={{ id: match.id }} className="group relative block overflow-hidden rounded-2xl border border-white/10 bg-black/30 p-4 transition hover:-translate-y-0.5 hover:border-amber-300/25"><div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-amber-300 via-cyan-300/40 to-transparent" /><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="text-xl">{sport.emoji}</span><span className="font-mono text-[8px] uppercase tracking-[.22em] text-white/35">{sport.name}</span>{live ? <LiveBadge /> : <TimeBadge>VÝSLEDEK</TimeBadge>}</div><span className="font-mono text-[8px] uppercase tracking-[.18em] text-white/25">{match.matchFormat === "2v2" ? "2V2" : "1V1"}</span></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><span className="truncate font-display text-lg font-black tracking-wide text-white">{match.teamA}</span><span className="rounded-xl border border-amber-300/20 bg-amber-300/[.06] px-3 py-2 font-mono text-lg font-black text-amber-100">{match.scoreA}:{match.scoreB}</span><span className="truncate text-right font-display text-lg font-black tracking-wide text-white">{match.teamB}</span></div><div className="mt-3 flex items-center justify-between text-[9px] uppercase tracking-[.18em] text-white/30"><span>{match.scheduledAt ? new Date(match.scheduledAt).toLocaleString("cs-CZ") : live ? "ŽIVÝ FEED" : "KONEC"}</span><ArrowUpRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></div></Link>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <div className="grid min-h-32 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] p-6 text-center"><div><Zap className="mx-auto h-6 w-6 text-amber-200/60" /><div className="mt-2 font-mono text-[10px] font-black uppercase tracking-[.26em] text-white/35">{title}</div><div className="mt-1 max-w-md text-sm text-white/25">{text}</div></div></div>; }
