import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Clock3, History, RotateCcw, ShieldCheck, Sparkles, Volume2, VolumeX } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { fetchMyWallet } from "@/lib/wallet-rpc";
import { useAuth } from "@/lib/auth";
import { cn } from "@/lib/utils";

const RED = new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const WHEEL = [0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const GRID = [
  [3,6,9,12,15,18,21,24,27,30,33,36],
  [2,5,8,11,14,17,20,23,26,29,32,35],
  [1,4,7,10,13,16,19,22,25,28,31,34],
];
const CHIPS = [10,50,100,500,1000,5000,10000];
const ROUND_SEC = 15;
const BETTING_SEC = 10;
const SPIN_SEC = 4;
type BetMap = Record<string, number>;

const roundNow = () => Math.floor(Date.now()/1000/ROUND_SEC);
const cycleNow = () => Math.floor(Date.now()/1000)%ROUND_SEC;
const color = (n:number) => n===0 ? "green" : RED.has(n) ? "red" : "black";
const mapBet = (key:string) => {
  if (/^\d+$/.test(key)) return { type:"number", value:key };
  if (key.startsWith("doz_")) return { type:"dozen", value:key.slice(4) };
  if (key === "1-18") return { type:"low", value:null };
  if (key === "19-36") return { type:"high", value:null };
  return { type:key, value:null };
};

export function RouletteCasinoTable(){
  const {user,balance=0,refreshProfile}=useAuth();
  const [chip,setChip]=useState(100); const [bets,setBets]=useState<BetMap>({}); const [serverBalance,setServerBalance]=useState(Number(balance));
  const [round,setRound]=useState(roundNow()); const [phase,setPhase]=useState<"BETTING"|"SPINNING"|"RESULT">("BETTING"); const [timeLeft,setTimeLeft]=useState(BETTING_SEC);
  const [winner,setWinner]=useState<number|null>(null); const [history,setHistory]=useState<number[]>([]); const [rotation,setRotation]=useState(0); const [muted,setMuted]=useState(false); const settled=useRef<number|null>(null);
  useEffect(()=>setServerBalance(Number(balance)),[balance]);
  const loadBets=useCallback(async(r:number)=>{ if(!user)return; const {data}=await supabase.from("roulette_bets").select("bet_type,bet_value,amount").eq("round_no",r).eq("user_id",user.id).eq("settled",false); const next:BetMap={}; for(const row of data??[]){const key=row.bet_type==="number"?String(row.bet_value):row.bet_type==="dozen"?`doz_${row.bet_value}`:row.bet_type==="low"?"1-18":row.bet_type==="high"?"19-36":row.bet_type; next[key]=(next[key]??0)+Number(row.amount??0);} setBets(next);},[user]);
  useEffect(()=>{void loadBets(round)},[round,loadBets]);
  const settle=useCallback(async(r:number)=>{const prev=r-1;if(prev<0||settled.current===prev)return;settled.current=prev;const {data,error}=await supabase.rpc("roulette_settle",{_round_no:prev});if(error){settled.current=null;return;}const result=Number((data as {result?:number}|null)?.result);if(!Number.isInteger(result)||result<0||result>36)return;setWinner(result);setHistory(xs=>[result,...xs].slice(0,12));const idx=WHEEL.indexOf(result);setRotation(x=>x+1800+(360-idx*(360/WHEEL.length)));await refreshProfile?.();if(user){const w=await fetchMyWallet();if(w)setServerBalance(w.balance);}},[refreshProfile,user]);
  useEffect(()=>{const tick=()=>{const r=roundNow(),c=cycleNow();if(r!==round){setRound(r);setBets({});settled.current=null;}if(c<BETTING_SEC){setPhase("BETTING");setTimeLeft(BETTING_SEC-c);}else if(c<BETTING_SEC+SPIN_SEC){setPhase("SPINNING");setTimeLeft(BETTING_SEC+SPIN_SEC-c);void settle(r);}else{setPhase("RESULT");setTimeLeft(ROUND_SEC-c);}};tick();const id=window.setInterval(tick,250);return()=>window.clearInterval(id)},[round,settle]);
  const total=useMemo(()=>Object.values(bets).reduce((s,v)=>s+v,0),[bets]); const canBet=!!user&&phase==="BETTING"&&serverBalance>=chip;
  const placeBet=useCallback(async(key:string)=>{if(!canBet)return;const m=mapBet(key);const {data,error}=await supabase.rpc("roulette_place_bet",{_round_no:round,_bet_type:m.type,_bet_value:m.value,_amount:chip});if(error){toast.error(error.message.includes("insufficient_balance")?"Nedostatek dolarů.":error.message.includes("round_closed")?"Sázky jsou uzavřené.":"Sázku se nepodařilo přijmout.");return;}const next=Number((data as {balance?:number}|null)?.balance);if(Number.isFinite(next))setServerBalance(next);setBets(x=>({...x,[key]:(x[key]??0)+chip}));},[canBet,round,chip]);
  const cancel=useCallback(async()=>{if(!total||phase!=="BETTING")return;const {data,error}=await supabase.rpc("roulette_cancel_bets",{_round_no:round});if(error){toast.error("Sázky už nejdou vrátit.");return;}setBets({});const next=Number((data as {balance?:number}|null)?.balance);if(Number.isFinite(next))setServerBalance(next);toast.success("Sázky vráceny." )},[phase,round,total]);
  return <div className="space-y-5 select-none">
    <section className="relative overflow-hidden rounded-[30px] border border-amber-300/20 bg-[radial-gradient(circle_at_50%_-20%,rgba(250,204,21,.16),transparent_44%),linear-gradient(135deg,#0b0d0f,#020304)] p-5 shadow-[0_35px_100px_-55px_rgba(250,204,21,.7)] sm:p-7">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/8 pb-4"><div><div className="aaa-meta text-amber-200/80">ROYAL EUROPEAN ROULETTE · VIP FLOOR</div><div className="mt-1 flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300"/><span className="font-mono text-[9px] uppercase tracking-[.22em] text-emerald-200">SERVER AUTHORITATIVE · PLAY MONEY</span></div></div><div className="flex items-center gap-2"><button onClick={()=>setMuted(x=>!x)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.03] text-white/50">{muted?<VolumeX className="h-4 w-4"/>:<Volume2 className="h-4 w-4"/>}</button><div className={cn("rounded-xl border px-4 py-2 font-mono text-[10px] font-black uppercase tracking-[.18em]",phase==="BETTING"?"border-emerald-300/20 bg-emerald-300/5 text-emerald-200":phase==="SPINNING"?"border-amber-300/25 bg-amber-300/5 text-amber-200":"border-cyan-300/20 bg-cyan-300/5 text-cyan-200")}>{phase==="BETTING"?`SÁZKY ${timeLeft}s`:phase==="SPINNING"?"KOLO V CHODU":"DALŠÍ KOLO · "+timeLeft+"s"}</div></div></div>
      <div className="grid gap-8 pt-6 lg:grid-cols-[minmax(280px,.8fr)_minmax(0,1.2fr)] lg:items-center">
        <div className="flex justify-center"><div className="relative aspect-square w-full max-w-[360px]"><div className="absolute inset-0 rounded-full bg-[conic-gradient(#0b0b0b_0deg_10deg,#9f1239_10deg_20deg,#0b0b0b_20deg_30deg,#166534_30deg_40deg,#0b0b0b_40deg_50deg)] shadow-[0_0_75px_rgba(245,158,11,.15)]"/><motion.div animate={{rotate:rotation}} transition={{duration:SPIN_SEC,ease:[.12,.8,.2,1]}} className="absolute inset-[7%] rounded-full border-[10px] border-amber-300/35 bg-[repeating-conic-gradient(from_0deg,#8f1028_0deg_9.73deg,#111827_9.73deg_19.46deg)] shadow-inner">{WHEEL.map((n,i)=>{const a=i*(360/WHEEL.length);return <span key={n} className="absolute left-1/2 top-1/2 origin-center font-mono text-[9px] font-black text-white/80" style={{transform:`rotate(${a}deg) translateY(-128px) rotate(${-a}deg)`}}>{n}</span>})}</motion.div><div className="absolute inset-[31%] rounded-full border-8 border-amber-200/35 bg-[radial-gradient(circle_at_32%_28%,#e7d7a3,#7a5520_42%,#0a0a0a_70%)] shadow-[inset_0_0_30px_rgba(0,0,0,.8),0_0_30px_rgba(245,158,11,.15)]"><div className="absolute inset-[16%] rounded-full border border-white/10 bg-black/70"/><div className="absolute -top-2 left-1/2 h-6 w-1 -translate-x-1/2 rounded-full bg-white shadow-[0_0_12px_white]"/><div className="absolute inset-0 grid place-items-center"><span className={cn("font-display text-5xl font-black",winner==null?"text-white/25":color(winner)==="red"?"text-red-300":color(winner)==="black"?"text-white":"text-emerald-300")}>{winner??"—"}</span></div></div><div className="absolute -top-1 left-1/2 z-30 -translate-x-1/2 text-amber-200 drop-shadow-[0_0_10px_rgba(250,204,21,.9)]">▼</div></div></div>
        <div><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-amber-200"/><span className="aaa-meta text-amber-100/70">TABLE INTELLIGENCE</span></div><div className="mt-4 grid grid-cols-3 gap-2"><Stat title="RESULT" value={winner==null?"--":String(winner)}/><Stat title="ROUND" value={String(round%10000).padStart(4,"0")}/><Stat title="POT" value={`$${total.toLocaleString("en-US")}`}/></div><div className="mt-4 rounded-2xl border border-white/8 bg-black/30 p-4"><div className="flex items-center gap-2 text-white/30"><History className="h-4 w-4"/><span className="aaa-meta">LAST 12</span></div><div className="mt-3 flex flex-wrap gap-1.5">{history.length?history.map((n,i)=><span key={`${n}-${i}`} className={cn("grid h-8 min-w-8 place-items-center rounded-lg border px-1 font-mono text-[9px] font-black",n===0?"border-emerald-300/20 bg-emerald-300/5 text-emerald-200":RED.has(n)?"border-rose-300/20 bg-rose-300/5 text-rose-200":"border-white/10 bg-white/[.03] text-white/70")}>{n}</span>):<span className="text-[10px] text-white/20">Čekám na první serverový výsledek.</span>}</div></div></div>
      </div>
    </section>
    <section className="relative overflow-hidden rounded-[30px] border border-emerald-300/15 bg-[radial-gradient(circle_at_50%_15%,rgba(6,95,70,.25),transparent_45%),linear-gradient(145deg,#064d3b,#021f17)] p-4 shadow-[0_30px_90px_-55px_rgba(16,185,129,.6)] sm:p-6">
      <div className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:36px_36px]"/>
      <div className="relative flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-4"><div><div className="aaa-meta text-amber-100/75">LIVE FELT · EUROPEAN SINGLE ZERO</div><div className="mt-1 text-xs text-white/35">Červená / černá / sudá / lichá / nízká / vysoká / tucet / číslo.</div></div><div className="flex items-center gap-2"><div className="rounded-xl border border-amber-300/20 bg-black/25 px-3 py-2 font-mono text-xs font-black text-amber-100">BALANCE ${serverBalance.toLocaleString("en-US")}</div>{total>0&&phase==="BETTING"&&<button onClick={()=>void cancel()} className="inline-flex items-center gap-1 rounded-xl border border-rose-300/20 bg-rose-300/5 px-3 py-2 font-mono text-[9px] font-black uppercase tracking-[.15em] text-rose-200"><RotateCcw className="h-3.5 w-3.5"/> VRÁTIT</button>}</div></div>
      <div className="mt-4 flex flex-wrap gap-2">{CHIPS.map(v=><button key={v} onClick={()=>setChip(v)} className={cn("relative grid h-12 min-w-12 place-items-center rounded-full border-4 font-mono text-[9px] font-black shadow-lg",chip===v?"border-amber-200 bg-amber-300 text-black scale-105":"border-white/20 bg-black/30 text-white/70")}>${v>=1000?`${v/1000}K`:v}</button>)}</div>
      <div className="mt-5 grid gap-2 md:grid-cols-[62px_1fr]"><button disabled={!canBet} onClick={()=>void placeBet("0")} className={cn("min-h-[126px] rounded-xl border text-lg font-black",canBet?"border-emerald-200/30 bg-emerald-950/80 text-emerald-100 hover:bg-emerald-900":"border-white/10 bg-black/20 text-white/20")}>0</button><div className="grid grid-cols-12 gap-1.5">{GRID.flat().map(n=><BetCell key={n} n={n} amount={bets[String(n)]??0} disabled={!canBet} onClick={()=>void placeBet(String(n))}/>)}</div></div>
      <div className="mt-2 grid gap-1.5 sm:grid-cols-6">{[["red","ČERVENÁ","2×"],["black","ČERNÁ","2×"],["even","SUDÁ","2×"],["odd","LICHÁ","2×"],["1-18","1–18","2×"],["19-36","19–36","2×"]].map(([k,t,m])=><Outside key={k} title={t} mult={m} amount={bets[k]??0} disabled={!canBet} onClick={()=>void placeBet(k)}/>)}</div>
      <div className="mt-2 grid gap-1.5 sm:grid-cols-3">{[["doz_1","1. TUCET"],["doz_2","2. TUCET"],["doz_3","3. TUCET"]].map(([k,t])=><Outside key={k} title={t} mult="3×" amount={bets[k]??0} disabled={!canBet} onClick={()=>void placeBet(k)}/>)}</div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-white/10 pt-4 font-mono text-[9px] uppercase tracking-[.18em]"><span className="text-white/25">{phase==="BETTING"?"Sázky jsou otevřené":"Sázky jsou uzavřené"}</span><span className="text-amber-100">TENT ROUND · ${total.toLocaleString("en-US")}</span></div>
    </section>
  </div>
}
function Stat({title,value}:{title:string;value:string}){return <div className="rounded-2xl border border-white/8 bg-black/25 p-3"><div className="aaa-meta">{title}</div><div className="mt-2 font-display text-xl font-black text-white">{value}</div></div>}
function Outside({title,mult,amount,disabled,onClick}:{title:string;mult:string;amount:number;disabled:boolean;onClick:()=>void}){return <button disabled={disabled} onClick={onClick} className={cn("relative min-h-16 rounded-xl border bg-black/20 px-3 py-2 transition",disabled?"cursor-not-allowed opacity-35":"hover:-translate-y-0.5 hover:border-amber-300/30",amount>0?"border-amber-300/50 ring-1 ring-amber-300/30":"border-white/10")}><span className="font-display text-sm font-black tracking-[.1em] text-white/85">{title}</span><span className="block mt-1 font-mono text-[8px] uppercase tracking-[.15em] text-amber-100/45">{mult}</span>{amount>0&&<Badge amount={amount}/>}</button>}
function BetCell({n,amount,disabled,onClick}:{n:number;amount:number;disabled:boolean;onClick:()=>void}){const tone=n===0?"border-emerald-300/20":RED.has(n)?"border-rose-300/25":"border-white/10";const bg=n===0?"bg-emerald-950/60":RED.has(n)?"bg-rose-950/50":"bg-black/25";return <button disabled={disabled} onClick={onClick} className={cn("relative min-h-16 rounded-lg border px-1 font-display text-lg font-black transition",tone,bg,disabled?"opacity-35 cursor-not-allowed":"hover:-translate-y-0.5 hover:brightness-125",amount>0&&"ring-2 ring-amber-300")}>{n}{amount>0&&<Badge amount={amount}/>}</button>}
function Badge({amount}:{amount:number}){return <span className="absolute -right-1 -top-1 rounded-full border border-amber-200/50 bg-amber-300 px-1.5 py-0.5 font-mono text-[8px] font-black text-black">${amount}</span>}
