import { useEffect, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { CalendarClock, Plus, Trophy, UsersRound, X, Zap } from "lucide-react";
import { SPORTS, type MatchFormat, type SportId } from "@/lib/matches";
import { createMatch } from "@/lib/matches-db";
import { createTournament, type TournamentFormat } from "@/lib/tournaments-db";
import { NICKNAMES_DATALIST_ID, NicknamesDatalist, useNicknames } from "@/lib/nicknames";
import { useAuth } from "@/lib/auth";

function toLocalInput(d: Date): string { const p=(n:number)=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; }
const TOURNAMENT_FORMATS: { id: TournamentFormat; label: string }[] = [{id:"round_robin",label:"Každý s každým"},{id:"single_elimination",label:"Pavouk"}];
const inputCls="w-full rounded-md border border-primary/30 bg-background/60 px-3 py-2 text-sm text-foreground outline-none transition focus:border-primary";
const labelCls="font-mono text-[10px] uppercase tracking-[0.3em] text-primary/70";

export function SportActionModal({ sport, image, onClose }:{sport:SportId;image?:string;onClose:()=>void}){
 const cfg=SPORTS[sport]; const navigate=useNavigate(); const {user,isAdmin}=useAuth(); const nicknames=useNicknames();
 const [tab,setTab]=useState<"match"|"tournament">("match"); const [matchFormat,setMatchFormat]=useState<MatchFormat>("1v1");
 const [playersA,setPlayersA]=useState<string[]>([cfg.defaultTeams[0]]); const [playersB,setPlayersB]=useState<string[]>([cfg.defaultTeams[1]]);
 const [busy,setBusy]=useState(false); const [err,setErr]=useState<string|null>(null);
 const [when,setWhen]=useState(()=>{const d=new Date();d.setHours(d.getHours()+1,0,0,0);return toLocalInput(d);});
 const [name,setName]=useState(""); const [format,setFormat]=useState<TournamentFormat>("round_robin"); const [teams,setTeams]=useState<string[]>(["",""]); const [tWhen,setTWhen]=useState(()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(18,0,0,0);return toLocalInput(d);});
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();window.addEventListener("keydown",onKey);const prev=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{window.removeEventListener("keydown",onKey);document.body.style.overflow=prev;};},[onClose]);
 useEffect(()=>{const n=matchFormat==="2v2"?2:1;setPlayersA(p=>Array.from({length:n},(_,i)=>p[i]??""));setPlayersB(p=>Array.from({length:n},(_,i)=>p[i]??""));},[matchFormat]);
 const setTeamCount=(n:number)=>setTeams(p=>Array.from({length:Math.max(2,Math.min(32,n))},(_,i)=>p[i]??""));
 async function submitMatch(e:React.FormEvent,live:boolean){e.preventDefault();if(!user){navigate({to:"/auth"});return;}setBusy(true);setErr(null);try{const a=playersA.map(x=>x.trim()).filter(Boolean),b=playersB.map(x=>x.trim()).filter(Boolean);if(matchFormat==="1v1"&&(a.length!==1||b.length!==1))throw new Error("1v1 vyžaduje jednoho hráče na každé straně.");if(matchFormat==="2v2"&&(a.length!==2||b.length!==2))throw new Error("2v2 vyžaduje dva hráče na každé straně.");const all=[...a,...b].map(x=>x.toLocaleLowerCase("cs-CZ"));if(new Set(all).size!==all.length)throw new Error("Hráč nesmí být ve dvou stranách zároveň.");let scheduledAt:number|undefined;if(!live){const ts=new Date(when).getTime();if(!ts||Number.isNaN(ts))throw new Error("Vyber platný termín");scheduledAt=ts;}const id=await createMatch({ownerId:user.id,sport,matchFormat,teamA:a.join(" & "),teamB:b.join(" & "),teamAPlayers:a,teamBPlayers:b,scheduledAt});onClose();navigate({to:"/match",search:{id}});}catch(e){setErr(e instanceof Error?e.message:"Nepodařilo se vytvořit zápas");}finally{setBusy(false);}}
 async function submitTournament(e:React.FormEvent){e.preventDefault();if(!user){navigate({to:"/auth"});return;}const filled=teams.map(t=>t.trim()).filter(Boolean);if(filled.length<2){setErr("Zadej alespoň 2 týmy.");return;}if(new Set(filled).size!==filled.length){setErr("Názvy týmů se nesmí opakovat.");return;}setBusy(true);setErr(null);try{const ts=new Date(tWhen).getTime();const id=await createTournament({name:name.trim()||`${cfg.name} turnaj`,sport,format,teams:filled,players:filled.map(()=>[]),scheduledAt:Number.isNaN(ts)?null:ts});onClose();navigate({to:"/tournament",search:{id}});}catch(e){setErr(e instanceof Error?e.message:"Nepodařilo se vytvořit turnaj");}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"><button aria-label="Zavřít" onClick={onClose} className="absolute inset-0 bg-background/80 backdrop-blur-sm"/><div role="dialog" aria-modal="true" className="relative z-10 max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl border border-primary/40 bg-background shadow-2xl sm:rounded-2xl">
  <div className="relative">{image&&<img src={image} alt={cfg.name} className="h-48 w-full object-cover sm:h-64"/>}<button onClick={onClose} aria-label="Zavřít" className="absolute right-3 top-3 rounded-full border border-primary/50 bg-background/70 p-2 text-primary"><X className="h-4 w-4"/></button></div>
  <div className="border-b border-primary/20 bg-primary/5 px-4 py-3"><p className="font-mono text-[10px] uppercase tracking-[.35em] text-primary/80">// {cfg.name}</p><h2 className="font-display text-3xl tracking-widest">{cfg.emoji} {cfg.name.toUpperCase()}</h2></div>
  <div className="px-4 pb-5 pt-4"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setTab("match");setErr(null);}} className={`rounded-md border px-3 py-2 text-xs font-semibold uppercase tracking-[.15em] ${tab==="match"?"border-primary bg-primary/15 text-primary":"border-primary/25 text-muted-foreground"}`}><CalendarClock className="mr-2 inline h-4 w-4"/>Zápas</button><button type="button" onClick={()=>{setTab("tournament");setErr(null);}} className={`rounded-md border px-3 py-2 text-xs font-semibold uppercase tracking-[.15em] ${tab==="tournament"?"border-accent bg-accent/15 text-accent":"border-primary/25 text-muted-foreground"}`}><Trophy className="mr-2 inline h-4 w-4"/>Turnaj</button></div>
   {!user&&<p className="mt-4 rounded-md border border-primary/30 bg-primary/5 px-3 py-2 text-xs text-muted-foreground">Pro vytvoření zápasu se musíš přihlásit.</p>}
   {tab==="match"?<form onSubmit={e=>submitMatch(e,false)} className="mt-4 space-y-4">
    <div className="grid grid-cols-2 gap-2 rounded-lg border border-primary/20 bg-primary/5 p-2">{(["1v1","2v2"] as MatchFormat[]).map(fmt=><button key={fmt} type="button" onClick={()=>setMatchFormat(fmt)} className={`rounded-md border px-3 py-2 text-xs font-black uppercase tracking-[.18em] ${matchFormat===fmt?"border-primary bg-primary/15 text-primary":"border-primary/15 text-muted-foreground"}`}>{fmt==="2v2"?<><UsersRound className="mr-1 inline h-4 w-4"/>2v2 · TÝMOVÝ ZÁPAS</>:"1v1 · INDIVIDUÁLNÍ"}</button>)}</div>
    <div className="grid gap-3 sm:grid-cols-2">{(["a","b"] as const).map(side=>{const list=side==="a"?playersA:playersB;const set=side==="a"?setPlayersA:setPlayersB;return <div key={side} className="rounded-xl border border-primary/20 bg-background/30 p-3"><label className={labelCls}>{matchFormat==="2v2"?`TÝM ${side.toUpperCase()}`:`HRÁČ ${side.toUpperCase()}`}</label><div className="mt-2 grid gap-2">{list.map((player,i)=><input key={i} list={NICKNAMES_DATALIST_ID} value={player} maxLength={60} placeholder={matchFormat==="2v2"?`Hráč ${i+1}`:side==="a"?cfg.defaultTeams[0]:cfg.defaultTeams[1]} onChange={e=>set((c)=>c.map((p,j)=>j===i?e.target.value:p))} className={inputCls}/>)}</div>{matchFormat==="2v2"&&<p className="mt-2 text-[10px] text-muted-foreground">2 hráči na straně · jeden týmový zápas.</p>}</div>;})}</div>
    <div><label className={labelCls}>Termín</label><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className={`mt-1.5 ${inputCls} font-mono text-primary`}/></div>{err&&<p className="text-xs text-destructive">{err}</p>}<div className="flex flex-col gap-2 sm:flex-row"><button type="submit" disabled={busy} className="flex-1 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">Naplánovat zápas</button><button type="button" disabled={busy} onClick={e=>submitMatch(e,true)} className="rounded-md border border-primary/40 px-4 py-2.5 text-sm font-semibold text-primary disabled:opacity-50"><Zap className="mr-1 inline h-4 w-4"/>Začít hned</button></div>
   </form>:<form onSubmit={submitTournament} className="mt-4 space-y-4"><p className="text-xs text-muted-foreground">Turnaj může založit pouze admin.</p><div className="grid gap-3 sm:grid-cols-2"><div><label className={labelCls}>Název</label><input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder={`${cfg.name} pohár`} className={`mt-1.5 ${inputCls}`}/></div><div><label className={labelCls}>Počet týmů</label><input type="number" min={2} max={32} value={teams.length} onChange={e=>setTeamCount(Number(e.target.value))} className={`mt-1.5 ${inputCls}`}/></div></div><div className="grid gap-2 sm:grid-cols-2">{TOURNAMENT_FORMATS.map(f=><button key={f.id} type="button" onClick={()=>setFormat(f.id)} className={`rounded-md border px-3 py-2 text-left ${format===f.id?"border-accent/60 bg-accent/15 text-accent":"border-primary/20 text-muted-foreground"}`}><span className="block font-semibold">{f.label}</span></button>)}</div><input type="datetime-local" value={tWhen} onChange={e=>setTWhen(e.target.value)} className={`${inputCls} font-mono text-primary`}/><div className="grid gap-2 sm:grid-cols-2">{teams.map((t,i)=><input key={i} value={t} placeholder={`Tým ${i+1}`} onChange={e=>setTeams(p=>p.map((v,j)=>j===i?e.target.value:v))} className={inputCls}/>)}</div>{err&&<p className="text-xs text-destructive">{err}</p>}<button type="submit" disabled={busy||!isAdmin} className="w-full rounded-md bg-accent px-4 py-2.5 text-sm font-semibold disabled:opacity-40">{busy?"Generuji…":"Vytvořit turnaj"}</button></form>}
   <NicknamesDatalist options={nicknames}/>
  </div>
 </div></div>;
}
