import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Crown, RotateCcw, ShieldCheck, Sparkles, Volume2, VolumeX } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { cn } from "@/lib/utils";

const RED = new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const WHEEL = [0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const BOARD = [[3,6,9,12,15,18,21,24,27,30,33,36],[2,5,8,11,14,17,20,23,26,29,32,35],[1,4,7,10,13,16,19,22,25,28,31,34]];
const CORNERS = [[1,2,4,5],[2,3,5,6],[4,5,7,8],[5,6,8,9],[7,8,10,11],[8,9,11,12],[10,11,13,14],[11,12,14,15],[13,14,16,17],[14,15,17,18],[16,17,19,20],[17,18,20,21],[19,20,22,23],[20,21,23,24],[22,23,25,26],[23,24,26,27],[25,26,28,29],[26,27,29,30],[28,29,31,32],[29,30,32,33],[31,32,34,35],[32,33,35,36]] as const;
const ROUND_SEC=15, BET_SEC=10, SPIN_SEC=3;
type BetMap=Record<string,number>;
const red=(n:number)=>RED.has(n);
const numberColor=(n:number)=>n===0?"text-emerald-100 bg-emerald-950/80 border-emerald-300/30":red(n)?"text-white bg-rose-950/80 border-rose-300/25":"text-white bg-slate-950/90 border-white/10";
const keyFor=(type:string,value:string|null)=>type==="number"?String(value):type==="low"?"1-18":type==="high"?"19-36":type==="dozen"?`doz_${value}`:type==="corner"?`corner_${value}`:type;
const mapBet=(key:string)=>{if(/^\d+$/.test(key))return{type:"number",value:key};if(key.startsWith("corner_"))return{type:"corner",value:key.slice(7)};if(key==="1-18")return{type:"low",value:null};if(key==="19-36")return{type:"high",value:null};if(key.startsWith("doz_"))return{type:"dozen",value:key.slice(4)};return{type:key,value:null};};
const roundNow=()=>Math.floor(Date.now()/1000/ROUND_SEC);
const cycleNow=()=>Math.floor(Date.now()/1000)%ROUND_SEC;

export function UltraRouletteTable(){
 const {user,balance=0,refreshProfile}=useAuth();
 const [chip,setChip]=useState(100); const [bets,setBets]=useState<BetMap>({}); const [serverBalance,setServerBalance]=useState(Number(balance));
 const [round,setRound]=useState(roundNow()); const [phase,setPhase]=useState<"BETTING"|"SPINNING"|"RESULT">("BETTING"); const [timeLeft,setTimeLeft]=useState(BET_SEC);
 const [winning,setWinning]=useState<number|null>(null); const [pending,setPending]=useState<number|null>(null); const [history,setHistory]=useState<number[]>([]); const [rotation,setRotation]=useState(0); const [sound,setSound]=useState(true); const settled=useRef<number|null>(null);
 useEffect(()=>setServerBalance(Number(balance)),[balance]);
 const load=useCallback(async(r:number)=>{if(!user)return;const {data}=await supabase.from("roulette_bets").select("bet_type,bet_value,amount").eq("round_no",r).eq("user_id",user.id).eq("settled",false);const next:BetMap={};for(const row of data??[]){const k=keyFor(row.bet_type,String(row.bet_value??""));next[k]=(next[k]??0)+Number(row.amount??0);}setBets(next);},[user]);
 useEffect(()=>{void load(round)},[load,round]);
 const settle=useCallback(async(r:number)=>{const prev=r-1;if(prev<0||settled.current===prev)return;settled.current=prev;const {data,error}=await supabase.rpc("roulette_settle",{_round_no:prev});if(error){settled.current=null;return;}const result=Number((data as {result?:number}|null)?.result);if(!Number.isInteger(result)||result<0||result>36)return;setPending(result);const idx=WHEEL.indexOf(result);const seg=360/WHEEL.length;setRotation(cur=>cur+360*7+(360-idx*seg));window.setTimeout(()=>{setWinning(result);setPending(null);setHistory(xs=>[result,...xs].slice(0,12));void refreshProfile?.();if(user)void supabase.from("profiles").select("balance").eq("id",user.id).maybeSingle().then(({data:row})=>{if(row?.balance!=null)setServerBalance(Number(row.balance));});},SPIN_SEC*1000);},[refreshProfile,user]);
 useEffect(()=>{const tick=()=>{const r=roundNow(),c=cycleNow();if(r!==round){setRound(r);setBets({});settled.current=null;}if(c<BET_SEC){setPhase("BETTING");setTimeLeft(BET_SEC-c);}else if(c<BET_SEC+SPIN_SEC){setPhase("SPINNING");setTimeLeft(BET_SEC+SPIN_SEC-c);void settle(r);}else{setPhase("RESULT");setTimeLeft(ROUND_SEC-c);}};tick();const id=window.setInterval(tick,250);return()=>window.clearInterval(id);},[round,settle]);
 const total=useMemo(()=>Object.values(bets).reduce((a,b)=>a+b,0),[bets]); const canBet=Boolean(user)&&phase==="BETTING"&&serverBalance>=chip;
 const place=useCallback(async(key:string)=>{if(!canBet)return;const m=mapBet(key);const {data,error}=await supabase.rpc("roulette_place_bet",{_round_no:round,_bet_type:m.type,_bet_value:m.value,_amount:chip});if(error){toast.error(error.message.includes("insufficient_balance")?"Nedostatek dolarů.":error.message.includes("round_closed")?"Sázky jsou uzavřené.":error.message.includes("invalid_corner")?"Neplatná čtveřice.":"Sázku se nepodařilo přijmout.");return;}const bal=Number((data as {balance?:number}|null)?.balance);if(Number.isFinite(bal))setServerBalance(bal);setBets(x=>({...x,[key]:(x[key]??0)+chip}));},[canBet,round,chip]);
 const cancel=useCallback(async()=>{if(phase!=="BETTING"||!total)return;const {data,error}=await supabase.rpc("roulette_cancel_bets",{_round_no:round});if(error){toast.error("Sázky už nejdou vrátit.");return;}setBets({});const bal=Number((data as {balance?:number}|null)?.balance);if(Number.isFinite(bal))setServerBalance(bal);toast.success("Sázky vráceny.");},[phase,total,round]);
 return <div className="space-y-5 select-none">
  <section className="relative overflow-hidden rounded-[34px] border border-amber-200/20 bg-[radial-gradient(circle_at_50%_10%,rgba(255,196,80,.14),transparent_28%),linear-gradient(180deg,#07130f,#020604)] p-4 shadow-[0_45px_140px_-55px_rgba(250,204,21,.45)] sm:p-7">
   <div className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.02)_1px,transparent_1px)] [background-size:38px_38px]"/>
   <div className="relative flex flex-wrap items-center justify-between gap-3 border-b border-white/8 pb-4"><div><div className="flex items-center gap-2 font-display text-xl tracking-[.14em] text-amber-100"><Crown className="h-4 w-4 text-amber-300"/> IMPERIAL ROULETTE // S++++ ULTRA</div><div className="mt-1 flex items-center gap-2 font-mono text-[8px] uppercase tracking-[.28em] text-emerald-200/70"><ShieldCheck className="h-3.5 w-3.5"/> server authoritative · european single zero · play money</div></div><div className="flex items-center gap-2"><button onClick={()=>setSound(x=>!x)} className="rounded-xl border border-white/10 bg-black/20 p-2 text-white/45 hover:text-white">{sound?<Volume2 className="h-4 w-4"/>:<VolumeX className="h-4 w-4"/>}</button><div className="rounded-xl border border-amber-200/15 bg-amber-200/[.04] px-3 py-2 font-mono text-[9px] font-black tracking-[.18em] text-amber-100">{phase==="BETTING"?`BETS OPEN · ${timeLeft}s`:phase==="SPINNING"?`BALL IN PLAY · ${timeLeft}s`:`NEXT ROUND · ${timeLeft}s`}</div></div></div>
   <div className="relative mt-6 grid gap-6 lg:grid-cols-[minmax(340px,520px)_1fr] lg:items-center">
    <div className="relative mx-auto aspect-square w-full max-w-[520px]">
     <div className="absolute inset-0 rounded-full border-[14px] border-amber-200/10 bg-[radial-gradient(circle_at_50%_42%,#17382a_0%,#0c2419_52%,#040b08_73%)] shadow-[inset_0_0_60px_rgba(0,0,0,.9),0_0_90px_rgba(34,197,94,.10)]"/>
     <div className="absolute inset-[7%] rounded-full border border-amber-200/15"/>
     {WHEEL.map((n,i)=>{const a=i*(360/WHEEL.length);return <div key={n} className="absolute left-1/2 top-1/2 h-1/2 w-px origin-bottom bg-white/7" style={{transform:`rotate(${a}deg) translateY(-100%)`}}><span className={cn("absolute -left-4 -top-4 grid h-8 w-8 place-items-center rounded-full border font-mono text-[9px] font-black",n===0?"border-emerald-300/40 bg-emerald-950 text-emerald-100":red(n)?"border-rose-300/30 bg-rose-950 text-white":"border-white/10 bg-slate-950 text-white")} style={{transform:`rotate(${-a}deg)`}}>{n}</span></div>})}
     <motion.div className="absolute inset-[10%] rounded-full border border-amber-300/20" animate={{rotate:rotation}} transition={{duration:SPIN_SEC,ease:[.12,.82,.22,1]}}/>
     <div className="absolute inset-[28%] rounded-full border-4 border-amber-200/20 bg-[radial-gradient(circle_at_35%_25%,#f4db8a,#8d6c24_38%,#16120a_73%)] shadow-[0_0_50px_rgba(250,204,21,.12),inset_0_0_20px_rgba(0,0,0,.7)]"><div className="absolute inset-[17%] rounded-full border border-white/10 bg-black/65"/><div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="aaa-meta text-amber-100/50">LATEST RESULT</div><div className={cn("mt-1 font-display text-5xl font-black",winning==null?"text-white/20":red(winning)?"text-rose-200":"text-white")}>{winning??"—"}</div></div></div></div>
     {pending!==null&&<motion.div className="absolute left-1/2 top-[4%] h-4 w-4 rounded-full bg-white shadow-[0_0_18px_6px_rgba(255,255,255,.85)]" animate={{y:[0,40,100,170,220,90,0],x:[0,35,-25,50,-35,20,0],scale:[1,1.1,.9,1.2,.8,1.1,1]}} transition={{duration:SPIN_SEC,ease:"easeInOut"}}/>}
     <div className="absolute -top-3 left-1/2 -translate-x-1/2 text-amber-100 drop-shadow-[0_0_12px_rgba(250,204,21,.9)]">▼</div>
    </div>
    <div className="grid gap-3 sm:grid-cols-2"><Panel label="TABLE STATUS"><div className="font-display text-3xl tracking-[.12em] text-amber-100">{phase}</div><p className="mt-1 text-xs text-white/30">{phase==="BETTING"?"Dealer is accepting bets.":phase==="SPINNING"?"Ball is still in motion. Result remains hidden until landing.":"Winning number confirmed."}</p></Panel><Panel label="BALANCE"><div className="font-display text-3xl text-emerald-100">${serverBalance.toLocaleString()}</div><p className="mt-1 text-xs text-white/30">server wallet</p></Panel><Panel label="LAST 12 RESULTS"><div className="flex flex-wrap gap-1.5">{history.map((n,i)=><span key={`${n}-${i}`} className={cn("grid h-8 w-8 place-items-center rounded-lg border font-mono text-[9px] font-black",numberColor(n))}>{n}</span>)}</div></Panel><Panel label="TABLE RULES"><div className="font-mono text-[9px] uppercase tracking-[.2em] text-white/35">straight 36× · corner 9× · dozen 3× · even-money 2×</div></Panel></div>
   </div>
  </section>
  <section className="rounded-[30px] border border-amber-200/12 bg-[#06100b]/95 p-4 shadow-[0_25px_90px_-55px_rgba(250,204,21,.35)] sm:p-6">
   <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/8 pb-4"><div><div className="aaa-meta text-amber-100/70">IMPERIAL BETTING CARPET</div><h2 className="mt-1 font-display text-2xl tracking-[.12em] text-white">SÁZKOVÝ STŮL</h2></div><div className="flex items-center gap-2"><div className="rounded-xl border border-amber-200/15 bg-amber-200/[.04] px-3 py-2 font-mono text-xs text-amber-100">${serverBalance.toLocaleString()}</div>{total>0&&phase==="BETTING"&&<button onClick={()=>void cancel()} className="inline-flex items-center gap-1 rounded-xl border border-rose-300/20 bg-rose-300/[.04] px-3 py-2 text-[9px] font-black uppercase tracking-[.16em] text-rose-200"><RotateCcw className="h-3.5 w-3.5"/> Vrátit</button>}</div></div>
   <div className="mt-4 flex flex-wrap gap-2">{[10,50,100,500,1000,5000,10000].map(v=><button key={v} onClick={()=>setChip(v)} disabled={phase!=="BETTING"} className={cn("rounded-full border px-4 py-2 font-mono text-[10px] font-black transition disabled:opacity-30",chip===v?"border-amber-200 bg-amber-200 text-black shadow-[0_0_24px_rgba(250,204,21,.25)]":"border-white/10 bg-white/[.03] text-white/55 hover:border-amber-200/30")}>${v.toLocaleString()}</button>)}</div>
   <div className="mt-4 grid grid-cols-12 gap-1.5">{BOARD.flat().map(n=><NumberBet key={n} n={n} amount={bets[String(n)]??0} disabled={!canBet} onClick={()=>void place(String(n))}/>)}</div>
   <div className="mt-4 grid gap-2 sm:grid-cols-3">{[["red","RED","2×"],["black","BLACK","2×"],["even","EVEN","2×"],["odd","ODD","2×"],["1-18","1–18","2×"],["19-36","19–36","2×"],["doz_1","1st DOZEN","3×"],["doz_2","2nd DOZEN","3×"],["doz_3","3rd DOZEN","3×"]].map(([k,l,o])=><QuickBet key={k} label={l} odds={o} amount={bets[k]??0} disabled={!canBet} click={()=>void place(k)}/>)}</div>
   <div className="mt-5 rounded-2xl border border-cyan-200/10 bg-cyan-200/[.02] p-4"><div className="flex items-center justify-between gap-3"><div><div className="aaa-meta text-cyan-100/70">CORNER BET // 4 ČÍSLA</div><p className="mt-1 text-xs text-white/30">Payout 9× · příklad 9, 8, 11, 12 = 8 · 9 · 11 · 12</p></div><Sparkles className="h-4 w-4 text-cyan-200"/></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{CORNERS.map(c=>{const k=`corner_${c.join(",")}`;return <button key={k} onClick={()=>void place(k)} disabled={!canBet} className={cn("rounded-xl border px-3 py-3 text-left transition disabled:opacity-30",bets[k]?"border-cyan-200/50 bg-cyan-200/10":"border-white/8 bg-black/20 hover:border-cyan-200/25")}><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-black tracking-[.16em] text-white">{c.join(" · ")}</span><span className="font-mono text-[9px] text-cyan-200">9×</span></div>{bets[k]?<div className="mt-1 text-[8px] text-amber-200">STAKE ${bets[k].toLocaleString()}</div>:<div className="mt-1 text-[8px] text-white/20">CORNER</div>}</button>})}</div></div>
   <div className="mt-4 flex items-center justify-between border-t border-white/8 pt-3 font-mono text-xs"><span className="text-white/25">TOTAL STAKE</span><span className="font-black text-amber-100">${total.toLocaleString()}</span></div>
  </section>
 </div>;
}
function Panel({label,children}:{label:string;children:React.ReactNode}){return <div className="rounded-2xl border border-white/8 bg-black/25 p-4"><div className="aaa-meta">{label}</div><div className="mt-2">{children}</div></div>}
function NumberBet({n,amount,disabled,onClick}:{n:number;amount:number;disabled:boolean;onClick:()=>void}){return <button disabled={disabled} onClick={onClick} className={cn("relative min-h-14 rounded-xl border font-display text-lg font-black transition hover:-translate-y-0.5 disabled:opacity-35",numberColor(n))}>{n}{amount>0&&<span className="absolute -right-1 -top-1 rounded-full bg-amber-200 px-1.5 py-0.5 font-mono text-[8px] font-black text-black">${amount}</span>}</button>}
function QuickBet({label,odds,amount,disabled,click}:{label:string;odds:string;amount:number;disabled:boolean;click:()=>void}){return <button disabled={disabled} onClick={click} className={cn("rounded-xl border border-white/8 bg-black/25 px-3 py-3 text-left transition hover:border-amber-200/25 disabled:opacity-35",amount>0&&"ring-1 ring-amber-200/60")}><div className="flex items-center justify-between"><span className="font-mono text-[9px] font-black tracking-[.2em] text-white/60">{label}</span><span className="font-mono text-[9px] text-amber-100">{odds}</span></div>{amount>0&&<div className="mt-1 text-[8px] text-amber-200">STAKE ${amount.toLocaleString()}</div>}</button>}
