/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BetsRouteImport } from './routes/bets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportReturnRouteImport } from './routes/support/return'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsRoute = BetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportReturnRoute = SupportReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => SupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/support/return': typeof SupportReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/support/return': typeof SupportReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/support/return': typeof SupportReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/profile'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/support/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/profile'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/support/return'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/profile'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/support/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BetsRoute: typeof BetsRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  MatchRoute: typeof MatchRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  TournamentRoute: typeof TournamentRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets': {
      id: '/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof BetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/return': {
      id: '/support/return'
      path: '/return'
      fullPath: '/support/return'
      preLoaderRoute: typeof SupportReturnRouteImport
      parentRoute: typeof SupportRoute
    }
  }
}

interface SupportRouteChildren {
  SupportReturnRoute: typeof SupportReturnRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportReturnRoute: SupportReturnRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BetsRoute: BetsRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  MatchRoute: MatchRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRouteWithChildren,
  TeamsRoute: TeamsRoute,
  TournamentRoute: TournamentRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
