/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as UltimateTeamRouteImport } from './routes/ultimate-team'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BetsRouteImport } from './routes/bets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlotsIndexRouteImport } from './routes/slots.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as SupportReturnRouteImport } from './routes/support/return'
import { Route as SlotsChmelovciCupRouteImport } from './routes/slots.chmelovci-cup'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const UltimateTeamRoute = UltimateTeamRouteImport.update({
  id: '/ultimate-team',
  path: '/ultimate-team',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsRoute = BetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsIndexRoute = SlotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlotsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportReturnRoute = SupportReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => SupportRoute,
} as any)
const SlotsChmelovciCupRoute = SlotsChmelovciCupRouteImport.update({
  id: '/chmelovci-cup',
  path: '/chmelovci-cup',
  getParentRoute: () => SlotsRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slots': typeof SlotsRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/ultimate-team': typeof UltimateTeamRoute
  '/venues': typeof VenuesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile/$id': typeof ProfileIdRoute
  '/slots/chmelovci-cup': typeof SlotsChmelovciCupRoute
  '/support/return': typeof SupportReturnRoute
  '/profile/': typeof ProfileIndexRoute
  '/slots/': typeof SlotsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/ultimate-team': typeof UltimateTeamRoute
  '/venues': typeof VenuesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile/$id': typeof ProfileIdRoute
  '/slots/chmelovci-cup': typeof SlotsChmelovciCupRoute
  '/support/return': typeof SupportReturnRoute
  '/profile': typeof ProfileIndexRoute
  '/slots': typeof SlotsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/rankings': typeof RankingsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slots': typeof SlotsRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/teams': typeof TeamsRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/ultimate-team': typeof UltimateTeamRoute
  '/venues': typeof VenuesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile/$id': typeof ProfileIdRoute
  '/slots/chmelovci-cup': typeof SlotsChmelovciCupRoute
  '/support/return': typeof SupportReturnRoute
  '/profile/': typeof ProfileIndexRoute
  '/slots/': typeof SlotsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arcade'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/mcp'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/slots'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/ultimate-team'
    | '/venues'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile/$id'
    | '/slots/chmelovci-cup'
    | '/support/return'
    | '/profile/'
    | '/slots/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arcade'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/mcp'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/ultimate-team'
    | '/venues'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile/$id'
    | '/slots/chmelovci-cup'
    | '/support/return'
    | '/profile'
    | '/slots'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arcade'
    | '/auth'
    | '/bets'
    | '/chat'
    | '/history'
    | '/live'
    | '/match'
    | '/mcp'
    | '/rankings'
    | '/schedule'
    | '/sitemap.xml'
    | '/slots'
    | '/support'
    | '/teams'
    | '/tournament'
    | '/tournaments'
    | '/ultimate-team'
    | '/venues'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile/$id'
    | '/slots/chmelovci-cup'
    | '/support/return'
    | '/profile/'
    | '/slots/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  AuthRoute: typeof AuthRoute
  BetsRoute: typeof BetsRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  MatchRoute: typeof MatchRoute
  McpRoute: typeof McpRoute
  RankingsRoute: typeof RankingsRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlotsRoute: typeof SlotsRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  TournamentRoute: typeof TournamentRoute
  TournamentsRoute: typeof TournamentsRoute
  UltimateTeamRoute: typeof UltimateTeamRoute
  VenuesRoute: typeof VenuesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultimate-team': {
      id: '/ultimate-team'
      path: '/ultimate-team'
      fullPath: '/ultimate-team'
      preLoaderRoute: typeof UltimateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets': {
      id: '/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof BetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots/': {
      id: '/slots/'
      path: '/'
      fullPath: '/slots/'
      preLoaderRoute: typeof SlotsIndexRouteImport
      parentRoute: typeof SlotsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/return': {
      id: '/support/return'
      path: '/return'
      fullPath: '/support/return'
      preLoaderRoute: typeof SupportReturnRouteImport
      parentRoute: typeof SupportRoute
    }
    '/slots/chmelovci-cup': {
      id: '/slots/chmelovci-cup'
      path: '/chmelovci-cup'
      fullPath: '/slots/chmelovci-cup'
      preLoaderRoute: typeof SlotsChmelovciCupRouteImport
      parentRoute: typeof SlotsRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SlotsRouteChildren {
  SlotsChmelovciCupRoute: typeof SlotsChmelovciCupRoute
  SlotsIndexRoute: typeof SlotsIndexRoute
}

const SlotsRouteChildren: SlotsRouteChildren = {
  SlotsChmelovciCupRoute: SlotsChmelovciCupRoute,
  SlotsIndexRoute: SlotsIndexRoute,
}

const SlotsRouteWithChildren = SlotsRoute._addFileChildren(SlotsRouteChildren)

interface SupportRouteChildren {
  SupportReturnRoute: typeof SupportReturnRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportReturnRoute: SupportReturnRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  AuthRoute: AuthRoute,
  BetsRoute: BetsRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  MatchRoute: MatchRoute,
  McpRoute: McpRoute,
  RankingsRoute: RankingsRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlotsRoute: SlotsRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  TeamsRoute: TeamsRoute,
  TournamentRoute: TournamentRoute,
  TournamentsRoute: TournamentsRoute,
  UltimateTeamRoute: UltimateTeamRoute,
  VenuesRoute: VenuesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
